// "Duel Grille" — 3x3 Immaculate-Grid-style board (rows = clubs, columns =
// nationality). Two players take turns claiming cells by naming a player who
// satisfies both the row and column criteria and hasn't already been used
// elsewhere in this grid; first to align 3 cells wins, like tic-tac-toe.
import { PLAYERS, Player } from '../data/players';
import { stripAcc } from './engine';

export type CriterionType = 'club' | 'nat';

export interface Criterion {
  type: CriterionType;
  value: string;
  label: string;
}

export interface DuelGrid {
  rows: Criterion[];
  cols: Criterion[];
}

function playerMatches(p: Player, c: Criterion): boolean {
  if (c.type === 'club') return p.clubs.includes(c.value);
  return p.nat === c.value;
}

export function cellCandidates(rowC: Criterion, colC: Criterion): Player[] {
  return PLAYERS.filter((p) => playerMatches(p, rowC) && playerMatches(p, colC));
}

export function matchesCriteria(name: string, rowC: Criterion, colC: Criterion): Player | null {
  const target = stripAcc(name.trim().toLowerCase());
  if (!target) return null;
  const found = PLAYERS.find((p) => stripAcc(p.n.toLowerCase()) === target);
  if (!found) return null;
  return playerMatches(found, rowC) && playerMatches(found, colC) ? found : null;
}

// Random 3-club x 3-criterion combos almost never give every one of the 9
// cells a real answer on this roster - rejection-sampling that at runtime
// effectively always exhausted its attempt budget and fell back to one
// fixed combo, which is why every grid looked the same. Precomputing the
// valid combos once (offline, verified against players.ts) and picking
// randomly among them fixes both the correctness and the repetition. Two
// pools: club x nationality
// (VALID_GRIDS) and club x club, i.e. "played for both" (VALID_GRIDS_CLUB_CLUB)
// so a grid isn't always nationality-based. Both were regenerated against
// the 653-player roster and biased to spread evenly across the top 5 clubs
// of France/Spain/Italy/Germany/England instead of only ever surfacing the
// same handful of European giants.
//
// VALID_GRIDS (club x nationality) is further restricted to only "easy"
// nationalities the average player will instantly recognise: FR, DE, IT,
// ES, PT, EN, BR, AR, MA, NL, BE, UY, DZ. Obscure ones (e.g. Bosnia,
// Bulgaria, Jamaica...) made the nationality column unguessable even when
// the club column was fine. VALID_GRIDS_CLUB_CLUB is unaffected (no
// nationality involved).
//
// Regenerate these lists if players.ts changes significantly (new players
// change which club/nationality/club pairs actually intersect).
const VALID_GRIDS: [string[], string[]][] = [
  [["Marseille","Real Madrid","Arsenal"], ["IT","DE","EN"]],
  [["Lille","Borussia Dortmund","Manchester United"], ["FR","BE","MA"]],
  [["Paris Saint-Germain","Inter","Manchester United"], ["BR","NL","MA"]],
  [["AC Milan","Liverpool","Arsenal"], ["BR","EN","BE"]],
  [["Roma","Manchester City","Chelsea"], ["AR","EN","NL"]],
  [["Lille","Real Madrid","Sevilla"], ["PT","BR","MA"]],
  [["Marseille","Lyon","Monaco"], ["FR","IT","DE"]],
  [["Monaco","Schalke 04","Chelsea"], ["DE","BE","ES"]],
  [["Napoli","Roma","Benfica"], ["AR","ES","BE"]],
  [["AC Milan","Borussia Dortmund","Manchester City"], ["EN","BE","DZ"]],
  [["RB Leipzig","Bayer Leverkusen","Manchester City"], ["DE","FR","ES"]],
  [["Lyon","Monaco","Bayern Munich"], ["BR","DE","PT"]],
  [["Monaco","Valencia","Schalke 04"], ["DE","ES","DZ"]],
  [["Lille","Real Madrid","Borussia Dortmund"], ["FR","EN","MA"]],
  [["Valencia","AC Milan","Roma"], ["AR","BR","NL"]],
  [["Lyon","Monaco","Sevilla"], ["BR","IT","PT"]],
  [["Valencia","AC Milan","Liverpool"], ["PT","AR","NL"]],
  [["Napoli","Manchester United","Benfica"], ["AR","BE","UY"]],
  [["Real Madrid","Sevilla","Manchester United"], ["PT","BR","MA"]],
  [["Paris Saint-Germain","Lille","Sevilla"], ["BR","PT","MA"]],
  [["Atlético Madrid","Napoli","Manchester United"], ["BE","AR","UY"]],
  [["Paris Saint-Germain","Real Madrid","Atlético Madrid"], ["AR","MA","UY"]],
  [["Monaco","Real Madrid","Schalke 04"], ["DE","BE","ES"]],
  [["Lyon","Monaco","AC Milan"], ["FR","PT","DZ"]],
  [["FC Barcelona","Valencia","Bayern Munich"], ["BR","PT","NL"]],
  [["Valencia","Inter","Benfica"], ["AR","BR","UY"]],
  [["Monaco","Schalke 04","Benfica"], ["DE","BE","ES"]],
  [["Juventus","RB Leipzig","Bayer Leverkusen"], ["FR","ES","DE"]],
  [["Paris Saint-Germain","Atlético Madrid","Manchester United"], ["AR","NL","MA"]],
  [["Monaco","Borussia Dortmund","Manchester City"], ["DE","IT","DZ"]],
  [["Paris Saint-Germain","Real Madrid","Borussia Dortmund"], ["EN","MA","DE"]],
  [["Valencia","AC Milan","Manchester City"], ["NL","FR","DZ"]],
  [["Paris Saint-Germain","Monaco","Arsenal"], ["BR","ES","DE"]],
  [["Valencia","Juventus","Napoli"], ["ES","AR","UY"]],
  [["Borussia Dortmund","Manchester United","Chelsea"], ["FR","MA","BE"]],
  [["Monaco","Valencia","Bayer Leverkusen"], ["FR","DE","ES"]],
  [["Monaco","Lille","Borussia Dortmund"], ["FR","BE","DZ"]],
  [["Marseille","Borussia Dortmund","Manchester City"], ["IT","DE","EN"]],
  [["Lyon","Lille","Manchester City"], ["NL","PT","DZ"]],
  [["Valencia","Schalke 04","Manchester City"], ["ES","DE","DZ"]],
  [["Atlético Madrid","Sevilla","Chelsea"], ["MA","AR","IT"]],
  [["Monaco","Borussia Dortmund","Manchester City"], ["FR","BE","DZ"]],
  [["Lille","Atlético Madrid","Borussia Dortmund"], ["BE","EN","MA"]],
  [["Schalke 04","Manchester City","Arsenal"], ["DE","ES","BE"]],
  [["Lille","Real Madrid","Atlético Madrid"], ["BE","EN","MA"]],
  [["Inter","Napoli","Benfica"], ["IT","BE","UY"]],
  [["Real Madrid","Atlético Madrid","Chelsea"], ["BE","MA","NL"]],
  [["Sevilla","Inter","Manchester United"], ["MA","BR","PT"]],
  [["Paris Saint-Germain","Bayern Munich","Arsenal"], ["BR","EN","NL"]],
  [["Lille","Real Madrid","Inter"], ["PT","NL","MA"]],
  [["Lyon","Lille","Valencia"], ["BR","NL","DZ"]],
  [["Atlético Madrid","Valencia","Liverpool"], ["PT","NL","UY"]],
  [["Real Madrid","Atlético Madrid","Manchester United"], ["EN","UY","NL"]],
  [["FC Barcelona","Manchester United","Benfica"], ["BR","PT","UY"]],
  [["Marseille","Manchester City","Arsenal"], ["IT","DE","EN"]],
  [["Marseille","Roma","Borussia Dortmund"], ["IT","DE","EN"]],
  [["Lyon","Lille","Valencia"], ["FR","NL","DZ"]],
  [["RB Leipzig","Bayer Leverkusen","Arsenal"], ["DE","FR","ES"]],
  [["Bayern Munich","RB Leipzig","Bayer Leverkusen"], ["DE","FR","ES"]],
  [["Paris Saint-Germain","Atlético Madrid","Chelsea"], ["AR","PT","MA"]],
  [["Sevilla","Inter","Chelsea"], ["AR","IT","MA"]],
  [["Lyon","AC Milan","Bayern Munich"], ["BR","NL","PT"]],
  [["Lyon","Valencia","Borussia Dortmund"], ["FR","DE","DZ"]],
  [["Lyon","Monaco","Benfica"], ["BR","IT","PT"]],
  [["Paris Saint-Germain","Atlético Madrid","Inter"], ["NL","MA","UY"]],
  [["Napoli","Liverpool","Benfica"], ["IT","BE","UY"]],
  [["Paris Saint-Germain","Lille","Real Madrid"], ["BR","PT","MA"]],
  [["FC Barcelona","Juventus","Napoli"], ["AR","FR","UY"]],
  [["Real Madrid","FC Barcelona","Benfica"], ["UY","ES","AR"]],
  [["AC Milan","Borussia Dortmund","Chelsea"], ["IT","EN","BE"]],
  [["Marseille","Borussia Dortmund","Liverpool"], ["FR","IT","EN"]],
  [["RB Leipzig","Bayer Leverkusen","Chelsea"], ["DE","FR","ES"]],
  [["Marseille","Borussia Dortmund","Liverpool"], ["IT","DE","EN"]],
  [["Valencia","Liverpool","Arsenal"], ["AR","BR","NL"]],
  [["Atlético Madrid","Napoli","Benfica"], ["AR","UY","IT"]],
  [["Atlético Madrid","Valencia","Juventus"], ["ES","PT","UY"]],
  [["Monaco","Roma","Schalke 04"], ["DE","BE","ES"]],
  [["Lille","AC Milan","Borussia Dortmund"], ["BE","EN","DZ"]],
  [["Roma","Schalke 04","Benfica"], ["DE","BE","ES"]],
  [["Sevilla","Inter","Borussia Dortmund"], ["FR","IT","MA"]],
  [["AC Milan","Roma","Borussia Dortmund"], ["IT","EN","BE"]],
  [["Lyon","FC Barcelona","AC Milan"], ["NL","IT","PT"]],
  [["Paris Saint-Germain","Real Madrid","Sevilla"], ["AR","BR","MA"]],
  [["Real Madrid","FC Barcelona","Juventus"], ["BR","UY","IT"]],
  [["Lyon","FC Barcelona","Liverpool"], ["BR","NL","PT"]],
  [["Monaco","Bayer Leverkusen","Manchester City"], ["FR","DE","ES"]],
  [["Marseille","AC Milan","Liverpool"], ["FR","IT","EN"]],
  [["Real Madrid","Valencia","Napoli"], ["UY","ES","AR"]],
  [["Lyon","Roma","RB Leipzig"], ["NL","DE","PT"]],
  [["Lyon","FC Barcelona","Sevilla"], ["BR","IT","PT"]],
  [["Real Madrid","Borussia Dortmund","Manchester United"], ["EN","DE","MA"]],
  [["Paris Saint-Germain","RB Leipzig","Bayer Leverkusen"], ["FR","ES","DE"]],
  [["Paris Saint-Germain","Sevilla","Chelsea"], ["FR","BR","MA"]],
  [["Roma","Schalke 04","Manchester City"], ["DE","BE","ES"]],
  [["Schalke 04","Manchester United","Arsenal"], ["DE","ES","BE"]],
  [["Real Madrid","Manchester United","Chelsea"], ["FR","EN","MA"]],
  [["Paris Saint-Germain","Lille","Borussia Dortmund"], ["FR","EN","MA"]],
  [["FC Barcelona","Napoli","Benfica"], ["AR","ES","UY"]],
  [["Marseille","AC Milan","Roma"], ["FR","IT","EN"]],
  [["Atlético Madrid","Valencia","Liverpool"], ["NL","AR","UY"]],
  [["Monaco","FC Barcelona","Bayern Munich"], ["BR","PT","ES"]],
  [["Valencia","Roma","Manchester City"], ["AR","BR","NL"]],
  [["Lyon","Manchester United","Liverpool"], ["BR","NL","PT"]],
  [["FC Barcelona","Valencia","Napoli"], ["AR","ES","UY"]],
  [["Lille","Inter","Borussia Dortmund"], ["FR","BE","MA"]],
  [["Monaco","AC Milan","Borussia Dortmund"], ["FR","IT","DZ"]],
  [["Marseille","Roma","Arsenal"], ["FR","IT","EN"]],
  [["Valencia","Napoli","Benfica"], ["ES","AR","UY"]],
  [["Juventus","Napoli","Benfica"], ["IT","UY","AR"]],
  [["Lyon","AC Milan","RB Leipzig"], ["FR","NL","PT"]],
  [["Napoli","Arsenal","Benfica"], ["AR","IT","BE"]],
  [["Marseille","Roma","Manchester City"], ["FR","IT","EN"]],
  [["Monaco","Schalke 04","Arsenal"], ["DE","BE","ES"]],
  [["Monaco","Schalke 04","Manchester United"], ["DE","BE","ES"]],
  [["Valencia","Juventus","Bayern Munich"], ["ES","PT","NL"]],
  [["Inter","Liverpool","Arsenal"], ["NL","BE","AR"]],
  [["FC Barcelona","RB Leipzig","Bayer Leverkusen"], ["FR","ES","DE"]],
  [["Monaco","Valencia","Borussia Dortmund"], ["FR","DE","DZ"]],
  [["Atlético Madrid","AC Milan","Manchester United"], ["EN","NL","BE"]],
  [["Monaco","Lille","Roma"], ["BR","PT","BE"]],
  [["FC Barcelona","Sevilla","Benfica"], ["AR","BR","IT"]],
  [["Inter","AC Milan","Liverpool"], ["PT","BE","AR"]],
  [["Real Madrid","Schalke 04","Manchester City"], ["DE","ES","BE"]],
  [["Marseille","Manchester City","Arsenal"], ["FR","IT","EN"]],
  [["Monaco","Bayern Munich","Bayer Leverkusen"], ["FR","DE","ES"]],
  [["Marseille","Manchester City","Chelsea"], ["IT","DE","EN"]],
  [["Marseille","Manchester City","Liverpool"], ["FR","IT","EN"]],
  [["Napoli","Manchester City","Benfica"], ["AR","IT","BE"]],
  [["Paris Saint-Germain","Sevilla","Manchester United"], ["FR","AR","MA"]],
  [["Lille","Sevilla","Inter"], ["PT","BR","MA"]],
  [["Marseille","Roma","Bayern Munich"], ["FR","DE","EN"]],
  [["Marseille","Real Madrid","Roma"], ["IT","DE","EN"]],
  [["Paris Saint-Germain","Marseille","AC Milan"], ["FR","IT","EN"]],
  [["FC Barcelona","Atlético Madrid","Valencia"], ["AR","PT","UY"]],
  [["AC Milan","Napoli","Benfica"], ["IT","BE","AR"]],
  [["Lille","Valencia","Manchester City"], ["FR","PT","DZ"]],
  [["Lyon","FC Barcelona","Valencia"], ["BR","NL","PT"]],
  [["Inter","Napoli","Benfica"], ["IT","AR","UY"]],
  [["Real Madrid","Atlético Madrid","Sevilla"], ["PT","ES","MA"]],
  [["Real Madrid","Atlético Madrid","Juventus"], ["PT","UY","NL"]],
  [["Monaco","AC Milan","Borussia Dortmund"], ["IT","BE","DZ"]],
  [["FC Barcelona","Atlético Madrid","Liverpool"], ["AR","PT","UY"]],
  [["Lyon","Monaco","Real Madrid"], ["BR","IT","PT"]],
  [["Atlético Madrid","Valencia","Juventus"], ["FR","NL","UY"]],
  [["Inter","Borussia Dortmund","Manchester United"], ["BE","MA","DE"]],
  [["Roma","RB Leipzig","Bayer Leverkusen"], ["DE","FR","ES"]],
  [["Monaco","AC Milan","Schalke 04"], ["BE","ES","DZ"]],
  [["Lille","Manchester United","Chelsea"], ["EN","NL","MA"]],
  [["Lyon","Borussia Dortmund","Manchester City"], ["FR","IT","DZ"]],
  [["Lille","Bayern Munich","Arsenal"], ["BR","EN","NL"]],
  [["Lille","Atlético Madrid","Chelsea"], ["PT","BE","MA"]],
  [["Inter","Napoli","Liverpool"], ["BE","AR","UY"]],
  [["Lille","AC Milan","Bayern Munich"], ["BR","EN","NL"]],
  [["Monaco","AC Milan","Manchester City"], ["PT","ES","DZ"]],
  [["Real Madrid","RB Leipzig","Bayer Leverkusen"], ["FR","DE","ES"]],
  [["Lyon","Monaco","Borussia Dortmund"], ["FR","IT","DZ"]],
  [["Paris Saint-Germain","Sevilla","Borussia Dortmund"], ["FR","IT","MA"]],
  [["Monaco","Schalke 04","Liverpool"], ["DE","BE","ES"]],
  [["Paris Saint-Germain","Real Madrid","Inter"], ["MA","UY","DE"]],
  [["Lille","Real Madrid","Chelsea"], ["PT","BR","MA"]],
  [["AC Milan","Borussia Dortmund","Liverpool"], ["IT","EN","BE"]],
  [["Juventus","Liverpool","Benfica"], ["IT","UY","BR"]],
  [["FC Barcelona","Inter","Napoli"], ["AR","FR","UY"]],
  [["FC Barcelona","Juventus","Napoli"], ["AR","IT","UY"]],
  [["Lyon","Lille","Manchester City"], ["FR","BR","DZ"]],
  [["Lille","Sevilla","Manchester United"], ["FR","PT","MA"]],
  [["Real Madrid","Napoli","Benfica"], ["UY","AR","IT"]],
  [["Real Madrid","Inter","Benfica"], ["BR","UY","AR"]],
  [["Atlético Madrid","Napoli","Benfica"], ["ES","BE","UY"]],
  [["Real Madrid","Inter","Borussia Dortmund"], ["FR","BE","MA"]],
  [["Atlético Madrid","Sevilla","Inter"], ["PT","MA","AR"]],
  [["Lyon","Sevilla","Bayern Munich"], ["FR","BR","PT"]],
  [["Atlético Madrid","Juventus","Manchester United"], ["NL","AR","UY"]],
  [["Schalke 04","Chelsea","Benfica"], ["DE","ES","BE"]],
  [["FC Barcelona","Napoli","Liverpool"], ["ES","IT","UY"]],
  [["Lyon","FC Barcelona","Bayern Munich"], ["BR","NL","DE"]],
  [["Napoli","Manchester United","Benfica"], ["AR","ES","UY"]],
  [["Paris Saint-Germain","Marseille","Manchester City"], ["FR","IT","EN"]],
  [["Valencia","Juventus","Benfica"], ["AR","BR","UY"]],
  [["Monaco","Valencia","Manchester City"], ["DE","PT","DZ"]],
  [["Roma","Schalke 04","Manchester United"], ["DE","BE","ES"]],
  [["Real Madrid","Roma","Schalke 04"], ["DE","ES","BE"]],
  [["Schalke 04","Chelsea","Arsenal"], ["DE","ES","BE"]],
  [["Paris Saint-Germain","Atlético Madrid","Sevilla"], ["AR","ES","MA"]],
  [["Marseille","AC Milan","Chelsea"], ["FR","IT","EN"]],
  [["FC Barcelona","Roma","Chelsea"], ["AR","BR","NL"]],
  [["Marseille","Roma","Manchester City"], ["IT","DE","EN"]],
  [["Real Madrid","Valencia","Napoli"], ["FR","UY","AR"]],
  [["RB Leipzig","Bayer Leverkusen","Liverpool"], ["DE","FR","ES"]],
  [["Roma","Schalke 04","Liverpool"], ["DE","BE","ES"]],
  [["FC Barcelona","Sevilla","Valencia"], ["AR","BR","ES"]],
  [["Lyon","Lille","AC Milan"], ["BR","PT","DZ"]],
  [["Lyon","AC Milan","Arsenal"], ["BR","NL","IT"]],
  [["Juventus","Inter","Benfica"], ["PT","IT","UY"]],
  [["AC Milan","Schalke 04","Manchester City"], ["ES","BE","DZ"]],
  [["Juventus","Bayern Munich","RB Leipzig"], ["PT","FR","NL"]],
  [["FC Barcelona","Sevilla","Roma"], ["AR","BR","IT"]],
  [["Bayern Munich","RB Leipzig","Manchester City"], ["PT","NL","ES"]],
  [["Monaco","AC Milan","Napoli"], ["IT","BE","ES"]],
  [["Atlético Madrid","Borussia Dortmund","Manchester United"], ["FR","EN","MA"]],
  [["Inter","AC Milan","Roma"], ["NL","BE","AR"]],
  [["Monaco","Sevilla","Roma"], ["BR","IT","PT"]],
  [["AC Milan","Bayern Munich","Chelsea"], ["EN","ES","NL"]],
  [["Monaco","Liverpool","Benfica"], ["BR","PT","BE"]],
  [["Lyon","Bayern Munich","RB Leipzig"], ["NL","DE","PT"]],
  [["FC Barcelona","Juventus","Benfica"], ["BR","ES","UY"]],
  [["Schalke 04","Manchester City","Chelsea"], ["DE","ES","BE"]],
  [["Real Madrid","Juventus","Benfica"], ["DE","UY","AR"]],
  [["Monaco","Borussia Dortmund","Schalke 04"], ["DE","BE","DZ"]],
  [["Lyon","AC Milan","Liverpool"], ["BR","NL","IT"]],
  [["Monaco","Chelsea","Benfica"], ["BR","PT","BE"]],
  [["Sevilla","Roma","Liverpool"], ["AR","IT","PT"]],
  [["Paris Saint-Germain","Lille","Manchester United"], ["FR","EN","MA"]],
  [["Borussia Dortmund","Manchester City","Arsenal"], ["EN","IT","BE"]],
  [["Marseille","Bayern Munich","Borussia Dortmund"], ["FR","DE","EN"]],
  [["Lille","Chelsea","Arsenal"], ["BE","BR","EN"]],
  [["Lyon","FC Barcelona","RB Leipzig"], ["FR","NL","PT"]],
  [["Lille","Inter","Chelsea"], ["FR","BE","MA"]],
  [["Atlético Madrid","AC Milan","Bayern Munich"], ["EN","PT","NL"]],
  [["Monaco","Valencia","Manchester City"], ["FR","PT","DZ"]],
  [["Monaco","FC Barcelona","Bayer Leverkusen"], ["FR","DE","ES"]],
  [["Marseille","Borussia Dortmund","Arsenal"], ["IT","DE","EN"]],
  [["Bayern Munich","RB Leipzig","Chelsea"], ["PT","NL","ES"]],
  [["Monaco","Bayern Munich","RB Leipzig"], ["DE","PT","ES"]],
  [["Monaco","Lille","Manchester City"], ["BR","PT","DZ"]],
  [["FC Barcelona","Napoli","Benfica"], ["ES","IT","UY"]],
  [["Lyon","Real Madrid","Roma"], ["BR","NL","PT"]],
  [["Monaco","Lille","Valencia"], ["BR","PT","DZ"]],
  [["Lille","Atlético Madrid","Manchester United"], ["BE","NL","MA"]],
  [["FC Barcelona","Sevilla","Juventus"], ["AR","BR","PT"]],
  [["Lyon","AC Milan","Borussia Dortmund"], ["FR","IT","DZ"]],
  [["Paris Saint-Germain","Borussia Dortmund","Manchester United"], ["EN","MA","DE"]],
  [["Paris Saint-Germain","Marseille","Roma"], ["IT","EN","DE"]],
  [["Lille","Sevilla","Inter"], ["FR","BR","MA"]],
  [["Valencia","Juventus","Liverpool"], ["PT","UY","NL"]],
  [["Schalke 04","Arsenal","Benfica"], ["DE","ES","BE"]],
  [["Lyon","AC Milan","Manchester City"], ["NL","IT","DZ"]],
  [["Monaco","Schalke 04","Manchester City"], ["BE","ES","DZ"]],
  [["Paris Saint-Germain","Sevilla","Chelsea"], ["AR","IT","MA"]],
  [["Paris Saint-Germain","Atlético Madrid","Borussia Dortmund"], ["FR","EN","MA"]],
  [["Atlético Madrid","Inter","Chelsea"], ["PT","MA","IT"]],
  [["Lyon","Monaco","Lille"], ["BR","PT","DZ"]],
  [["Roma","Schalke 04","Arsenal"], ["DE","BE","ES"]],
  [["Lyon","RB Leipzig","Chelsea"], ["NL","DE","PT"]],
  [["FC Barcelona","Bayern Munich","Bayer Leverkusen"], ["FR","ES","DE"]],
  [["FC Barcelona","Juventus","Manchester United"], ["AR","BR","UY"]],
  [["Marseille","Roma","Arsenal"], ["IT","DE","EN"]],
  [["Valencia","Manchester United","Benfica"], ["ES","BR","UY"]],
  [["AC Milan","Borussia Dortmund","Manchester City"], ["FR","IT","DZ"]],
  [["Lyon","Borussia Dortmund","Manchester City"], ["IT","DE","DZ"]],
  [["Lille","Valencia","AC Milan"], ["BR","NL","DZ"]],
  [["AC Milan","Bayern Munich","RB Leipzig"], ["ES","PT","NL"]],
  [["Lille","Sevilla","Chelsea"], ["FR","BR","MA"]],
  [["Lyon","Monaco","Valencia"], ["DE","PT","DZ"]],
  [["Paris Saint-Germain","Borussia Dortmund","Chelsea"], ["IT","MA","DE"]],
  [["Borussia Dortmund","Schalke 04","Manchester City"], ["DE","BE","DZ"]],
  [["Atlético Madrid","Inter","Borussia Dortmund"], ["BE","MA","IT"]],
  [["Roma","Borussia Dortmund","Arsenal"], ["IT","BE","EN"]],
  [["Lille","AC Milan","Arsenal"], ["BR","EN","NL"]],
  [["Lyon","Monaco","Sevilla"], ["FR","BR","PT"]],
  [["AC Milan","Bayern Munich","Manchester City"], ["BR","EN","PT"]],
  [["RB Leipzig","Bayer Leverkusen","Manchester United"], ["DE","FR","ES"]],
  [["Schalke 04","Manchester City","Manchester United"], ["DE","ES","BE"]],
  [["Atlético Madrid","Roma","Liverpool"], ["EN","PT","BE"]],
  [["Atlético Madrid","Sevilla","Borussia Dortmund"], ["FR","MA","IT"]],
  [["Lille","Manchester United","Liverpool"], ["BE","EN","NL"]],
  [["Lille","Borussia Dortmund","Manchester City"], ["FR","EN","DZ"]],
  [["Lille","Manchester City","Arsenal"], ["BE","BR","EN"]],
  [["Napoli","Liverpool","Benfica"], ["ES","BE","UY"]],
  [["Paris Saint-Germain","Juventus","Manchester United"], ["AR","PT","UY"]],
  [["Monaco","Juventus","Bayer Leverkusen"], ["FR","DE","ES"]],
  [["Real Madrid","Sevilla","Chelsea"], ["BR","MA","AR"]],
  [["Atlético Madrid","Borussia Dortmund","Chelsea"], ["FR","BE","MA"]],
  [["Marseille","AC Milan","Manchester City"], ["FR","IT","EN"]],
  [["Marseille","Liverpool","Arsenal"], ["FR","IT","EN"]],
  [["Paris Saint-Germain","Atlético Madrid","Manchester United"], ["ES","MA","UY"]],
  [["FC Barcelona","Inter","Napoli"], ["AR","IT","UY"]],
  [["Monaco","AC Milan","Manchester City"], ["IT","ES","DZ"]],
  [["Lyon","Valencia","AC Milan"], ["FR","NL","DZ"]],
  [["Paris Saint-Germain","Manchester United","Benfica"], ["AR","BR","UY"]],
  [["Lyon","RB Leipzig","Liverpool"], ["NL","DE","PT"]],
  [["AC Milan","Roma","Liverpool"], ["EN","BE","AR"]],
  [["Paris Saint-Germain","FC Barcelona","Valencia"], ["PT","NL","UY"]],
  [["FC Barcelona","Napoli","Manchester United"], ["AR","FR","UY"]],
  [["Sevilla","Borussia Dortmund","Chelsea"], ["FR","IT","MA"]],
  [["Sevilla","Juventus","Arsenal"], ["AR","IT","BR"]],
  [["Valencia","Inter","Benfica"], ["AR","UY","DE"]],
  [["Lille","Atlético Madrid","Inter"], ["PT","BE","MA"]],
  [["Lille","Roma","Arsenal"], ["BR","EN","NL"]],
  [["Lille","AC Milan","Chelsea"], ["BE","BR","EN"]],
  [["Lyon","Inter","RB Leipzig"], ["NL","DE","PT"]],
  [["RB Leipzig","Chelsea","Arsenal"], ["FR","ES","NL"]],
  [["Sevilla","Inter","Chelsea"], ["FR","MA","BR"]],
  [["Atlético Madrid","Manchester City","Arsenal"], ["EN","NL","AR"]],
  [["Valencia","Borussia Dortmund","Manchester City"], ["FR","DE","DZ"]],
  [["Lille","Roma","Manchester United"], ["BE","EN","NL"]],
  [["Juventus","Inter","Liverpool"], ["IT","UY","NL"]],
  [["Paris Saint-Germain","Real Madrid","Napoli"], ["AR","IT","UY"]],
  [["Lille","AC Milan","Borussia Dortmund"], ["FR","EN","DZ"]],
  [["Juventus","Bayern Munich","Bayer Leverkusen"], ["FR","ES","DE"]],
  [["Paris Saint-Germain","Napoli","Liverpool"], ["AR","IT","UY"]],
  [["Real Madrid","Atlético Madrid","Manchester United"], ["UY","ES","MA"]],
  [["Schalke 04","Manchester City","Liverpool"], ["DE","ES","BE"]],
  [["Paris Saint-Germain","Manchester City","Liverpool"], ["AR","BR","EN"]],
  [["Lyon","Juventus","RB Leipzig"], ["NL","DE","PT"]],
  [["Lyon","Juventus","Bayern Munich"], ["FR","NL","PT"]],
  [["Valencia","Inter","Napoli"], ["AR","UY","FR"]],
  [["Marseille","AC Milan","Borussia Dortmund"], ["FR","IT","EN"]],
  [["Atlético Madrid","Sevilla","Inter"], ["FR","MA","AR"]],
  [["Paris Saint-Germain","Sevilla","Inter"], ["FR","IT","MA"]],
  [["Schalke 04","Manchester City","Benfica"], ["DE","ES","BE"]],
  [["Paris Saint-Germain","Inter","Napoli"], ["AR","IT","UY"]],
  [["Bayern Munich","Manchester United","Liverpool"], ["EN","PT","NL"]],
  [["Lille","Real Madrid","Manchester City"], ["BE","BR","EN"]],
  [["Inter","Napoli","Chelsea"], ["IT","BE","FR"]],
  [["Juventus","Napoli","Manchester United"], ["ES","UY","AR"]],
  [["Lille","FC Barcelona","RB Leipzig"], ["FR","PT","NL"]],
  [["FC Barcelona","AC Milan","Bayern Munich"], ["BR","PT","NL"]],
  [["Manchester City","Liverpool","Arsenal"], ["EN","AR","BR"]],
  [["Lyon","Monaco","FC Barcelona"], ["BR","IT","DE"]],
  [["Lille","Borussia Dortmund","Chelsea"], ["FR","BE","MA"]],
  [["Paris Saint-Germain","Juventus","Napoli"], ["AR","IT","UY"]],
  [["Monaco","Schalke 04","Manchester City"], ["DE","BE","ES"]],
  [["FC Barcelona","Valencia","Juventus"], ["FR","PT","UY"]],
  [["Lyon","Juventus","AC Milan"], ["BR","NL","IT"]],
  [["AC Milan","Borussia Dortmund","Arsenal"], ["IT","EN","BE"]],
  [["Lille","Borussia Dortmund","Manchester United"], ["FR","EN","MA"]],
  [["Marseille","Borussia Dortmund","Chelsea"], ["FR","IT","EN"]],
  [["Real Madrid","Valencia","Benfica"], ["UY","ES","AR"]],
  [["Valencia","Bayern Munich","Bayer Leverkusen"], ["ES","FR","DE"]],
  [["Schalke 04","Liverpool","Benfica"], ["DE","ES","BE"]],
  [["Lyon","Valencia","Manchester City"], ["BR","NL","PT"]],
  [["AC Milan","Bayern Munich","Manchester United"], ["EN","ES","NL"]],
  [["Juventus","Napoli","Liverpool"], ["IT","UY","AR"]],
  [["Lille","Atlético Madrid","Manchester City"], ["BE","EN","NL"]],
  [["Monaco","Inter","Roma"], ["BR","IT","BE"]],
  [["Valencia","RB Leipzig","Bayer Leverkusen"], ["ES","FR","DE"]],
  [["Monaco","RB Leipzig","Bayer Leverkusen"], ["FR","DE","ES"]],
  [["Juventus","RB Leipzig","Manchester City"], ["PT","ES","NL"]],
  [["Juventus","Inter","Napoli"], ["FR","UY","AR"]],
  [["Marseille","AC Milan","Arsenal"], ["FR","IT","EN"]],
  [["Lyon","Lille","Bayern Munich"], ["BR","NL","PT"]],
  [["AC Milan","Bayern Munich","Manchester City"], ["EN","PT","NL"]],
  [["Paris Saint-Germain","Juventus","Manchester United"], ["PT","NL","UY"]],
  [["FC Barcelona","Atlético Madrid","Inter"], ["AR","NL","UY"]],
  [["Marseille","Borussia Dortmund","Arsenal"], ["FR","IT","EN"]],
  [["Monaco","Manchester City","Liverpool"], ["BR","IT","BE"]],
  [["Marseille","Real Madrid","AC Milan"], ["FR","IT","EN"]],
  [["FC Barcelona","Juventus","RB Leipzig"], ["DE","PT","NL"]],
  [["Atlético Madrid","Inter","Liverpool"], ["NL","BE","UY"]],
  [["Monaco","Valencia","Bayern Munich"], ["BR","PT","ES"]],
  [["Lyon","Sevilla","AC Milan"], ["BR","IT","PT"]],
  [["Paris Saint-Germain","Real Madrid","Juventus"], ["BR","IT","UY"]],
  [["Marseille","Bayern Munich","Arsenal"], ["FR","DE","EN"]],
  [["Lille","Real Madrid","Borussia Dortmund"], ["FR","BE","MA"]],
  [["Roma","Schalke 04","Chelsea"], ["DE","BE","ES"]],
  [["Paris Saint-Germain","Lille","Atlético Madrid"], ["PT","NL","MA"]],
  [["Schalke 04","Liverpool","Arsenal"], ["DE","ES","BE"]],
  [["Atlético Madrid","Valencia","Benfica"], ["PT","AR","UY"]],
  [["Lille","Real Madrid","Sevilla"], ["FR","PT","MA"]],
  [["Sevilla","Valencia","Manchester City"], ["AR","ES","BR"]],
  [["FC Barcelona","Valencia","Benfica"], ["BR","DE","UY"]],
  [["Real Madrid","Schalke 04","Arsenal"], ["DE","ES","BE"]],
  [["Paris Saint-Germain","Napoli","Manchester United"], ["AR","ES","UY"]],
  [["Paris Saint-Germain","Napoli","Benfica"], ["AR","ES","UY"]],
  [["Napoli","Roma","Arsenal"], ["AR","IT","BE"]],
  [["Valencia","Juventus","Bayer Leverkusen"], ["ES","FR","DE"]],
  [["FC Barcelona","Valencia","RB Leipzig"], ["ES","PT","NL"]],
  [["Paris Saint-Germain","Inter","Chelsea"], ["NL","MA","DE"]],
  [["Lyon","Bayern Munich","RB Leipzig"], ["FR","NL","DE"]],
  [["Lille","Sevilla","Chelsea"], ["FR","PT","MA"]],
  [["Real Madrid","Sevilla","Borussia Dortmund"], ["FR","MA","IT"]],
  [["Monaco","Roma","Bayer Leverkusen"], ["FR","DE","ES"]],
  [["FC Barcelona","Atlético Madrid","Juventus"], ["AR","ES","UY"]],
  [["Paris Saint-Germain","Marseille","Manchester City"], ["IT","EN","DE"]],
  [["Lyon","AC Milan","Bayern Munich"], ["FR","BR","NL"]],
  [["Paris Saint-Germain","Manchester United","Benfica"], ["AR","PT","UY"]],
  [["FC Barcelona","Valencia","Inter"], ["BR","DE","UY"]],
  [["Real Madrid","Inter","Benfica"], ["PT","UY","BE"]],
  [["Bayern Munich","Manchester United","Chelsea"], ["EN","PT","NL"]],
  [["Monaco","Bayer Leverkusen","Arsenal"], ["FR","DE","ES"]],
  [["Marseille","Bayern Munich","Manchester City"], ["FR","DE","EN"]],
  [["Lille","Manchester City","Arsenal"], ["BR","EN","NL"]],
  [["Atlético Madrid","Valencia","Inter"], ["PT","AR","UY"]],
  [["Juventus","AC Milan","Roma"], ["NL","AR","BR"]],
  [["Paris Saint-Germain","Bayern Munich","Manchester City"], ["BR","EN","PT"]],
  [["Monaco","Bayer Leverkusen","Liverpool"], ["FR","DE","ES"]],
  [["Schalke 04","Liverpool","Chelsea"], ["DE","ES","BE"]],
  [["Lyon","Lille","Juventus"], ["BR","NL","PT"]],
  [["Paris Saint-Germain","Borussia Dortmund","Chelsea"], ["FR","IT","MA"]],
  [["Valencia","Juventus","AC Milan"], ["PT","AR","BR"]],
  [["Lille","Bayern Munich","Chelsea"], ["PT","EN","NL"]],
  [["Monaco","Sevilla","Valencia"], ["BR","PT","ES"]],
  [["Real Madrid","Inter","Borussia Dortmund"], ["DE","MA","IT"]],
  [["Valencia","Roma","RB Leipzig"], ["ES","PT","NL"]],
  [["Real Madrid","AC Milan","Roma"], ["BE","AR","NL"]],
  [["AC Milan","Manchester United","Arsenal"], ["BR","BE","NL"]],
  [["Paris Saint-Germain","Roma","Arsenal"], ["BR","EN","NL"]],
  [["Atlético Madrid","Liverpool","Arsenal"], ["EN","NL","AR"]],
  [["Lyon","RB Leipzig","Manchester City"], ["NL","DE","PT"]],
];

const VALID_GRIDS_CLUB_CLUB: [string[], string[]][] = [
  [["Lille","FC Barcelona","Manchester United"], ["Paris Saint-Germain","Real Madrid","Bayern Munich"]],
  [["Lyon","Sevilla","Borussia Dortmund"], ["Chelsea","Manchester City","Marseille"]],
  [["Valencia","Liverpool","Arsenal"], ["Atlético Madrid","Inter","Juventus"]],
  [["Monaco","Bayern Munich","RB Leipzig"], ["AC Milan","Roma","Bayer Leverkusen"]],
  [["Real Madrid","Juventus","Arsenal"], ["Schalke 04","Benfica","Napoli"]],
  [["Napoli","RB Leipzig","Benfica"], ["Chelsea","Paris Saint-Germain","Roma"]],
  [["FC Barcelona","Sevilla","Manchester City"], ["Borussia Dortmund","Atlético Madrid","Schalke 04"]],
  [["Marseille","Lyon","Liverpool"], ["AC Milan","Monaco","Inter"]],
  [["Lille","Sevilla","Manchester United"], ["Inter","Liverpool","Valencia"]],
  [["Lille","Bayer Leverkusen","Manchester United"], ["Paris Saint-Germain","Monaco","Roma"]],
  [["Marseille","Valencia","Bayer Leverkusen"], ["Juventus","Arsenal","FC Barcelona"]],
  [["Lyon","Borussia Dortmund","RB Leipzig"], ["Chelsea","AC Milan","Bayern Munich"]],
  [["Atlético Madrid","Valencia","Chelsea"], ["Manchester City","Real Madrid","Benfica"]],
  [["Atlético Madrid","Napoli","Schalke 04"], ["FC Barcelona","Real Madrid","Juventus"]],
  [["Napoli","Borussia Dortmund","Schalke 04"], ["Arsenal","Paris Saint-Germain","Lille"]],
  [["Manchester City","Manchester United","Benfica"], ["Bayern Munich","AC Milan","Inter"]],
  [["Monaco","Sevilla","RB Leipzig"], ["Manchester City","Liverpool","Roma"]],
  [["Marseille","Monaco","Liverpool"], ["Manchester United","Lyon","Bayer Leverkusen"]],
  [["Marseille","Roma","Bayern Munich"], ["Chelsea","Lyon","Bayer Leverkusen"]],
  [["Atlético Madrid","Inter","RB Leipzig"], ["AC Milan","Sevilla","Paris Saint-Germain"]],
  [["Borussia Dortmund","Schalke 04","Arsenal"], ["Lille","Benfica","Juventus"]],
  [["FC Barcelona","Valencia","Arsenal"], ["Napoli","Real Madrid","Schalke 04"]],
  [["Lille","FC Barcelona","Valencia"], ["Napoli","Real Madrid","Sevilla"]],
  [["AC Milan","Chelsea","Benfica"], ["Paris Saint-Germain","Juventus","Borussia Dortmund"]],
  [["Monaco","Bayern Munich","Liverpool"], ["Atlético Madrid","Inter","Bayer Leverkusen"]],
  [["Marseille","RB Leipzig","Manchester United"], ["Manchester City","Bayern Munich","Roma"]],
  [["Marseille","Lyon","Monaco"], ["Manchester City","Inter","Roma"]],
  [["Atlético Madrid","Juventus","Manchester United"], ["Liverpool","Chelsea","Lyon"]],
  [["Borussia Dortmund","RB Leipzig","Arsenal"], ["Paris Saint-Germain","Bayer Leverkusen","AC Milan"]],
  [["Lille","FC Barcelona","Benfica"], ["Real Madrid","Valencia","Schalke 04"]],
  [["FC Barcelona","Napoli","Schalke 04"], ["Sevilla","Real Madrid","Lille"]],
  [["Juventus","Napoli","Arsenal"], ["Paris Saint-Germain","Valencia","Sevilla"]],
  [["AC Milan","Bayer Leverkusen","Benfica"], ["Chelsea","Borussia Dortmund","Roma"]],
  [["Monaco","Manchester City","Liverpool"], ["Atlético Madrid","Manchester United","Lyon"]],
  [["Marseille","Inter","RB Leipzig"], ["Bayern Munich","Chelsea","Roma"]],
  [["Inter","Manchester United","Liverpool"], ["Benfica","Bayern Munich","Marseille"]],
  [["Atlético Madrid","Valencia","RB Leipzig"], ["Manchester City","FC Barcelona","AC Milan"]],
  [["Lyon","Juventus","Bayer Leverkusen"], ["Real Madrid","Arsenal","Monaco"]],
  [["Napoli","Borussia Dortmund","Arsenal"], ["Sevilla","Paris Saint-Germain","Lille"]],
  [["Sevilla","Borussia Dortmund","Schalke 04"], ["FC Barcelona","Paris Saint-Germain","Lille"]],
  [["Lyon","Valencia","Schalke 04"], ["Real Madrid","Manchester City","Juventus"]],
  [["AC Milan","Napoli","Bayer Leverkusen"], ["Chelsea","Inter","Marseille"]],
  [["Roma","Bayer Leverkusen","Manchester United"], ["Liverpool","Bayern Munich","Monaco"]],
  [["Atlético Madrid","RB Leipzig","Benfica"], ["Liverpool","Chelsea","Bayern Munich"]],
  [["Paris Saint-Germain","Atlético Madrid","Roma"], ["AC Milan","Benfica","Monaco"]],
  [["Valencia","Inter","RB Leipzig"], ["FC Barcelona","Manchester City","Sevilla"]],
  [["Borussia Dortmund","Schalke 04","Manchester United"], ["Real Madrid","Arsenal","Juventus"]],
  [["Lyon","Lille","Napoli"], ["Paris Saint-Germain","Marseille","Juventus"]],
  [["Marseille","Valencia","Napoli"], ["Lille","Arsenal","Manchester United"]],
  [["Lyon","Borussia Dortmund","Schalke 04"], ["Real Madrid","Manchester City","Bayern Munich"]],
  [["FC Barcelona","Sevilla","Inter"], ["Atlético Madrid","Chelsea","Liverpool"]],
  [["Monaco","Inter","RB Leipzig"], ["FC Barcelona","AC Milan","Roma"]],
  [["RB Leipzig","Bayer Leverkusen","Benfica"], ["Bayern Munich","Paris Saint-Germain","Roma"]],
  [["Monaco","Bayer Leverkusen","Benfica"], ["Borussia Dortmund","Chelsea","Liverpool"]],
  [["Atlético Madrid","Sevilla","Valencia"], ["Manchester City","AC Milan","Arsenal"]],
  [["Lyon","Napoli","Schalke 04"], ["Real Madrid","Arsenal","Juventus"]],
  [["Marseille","Real Madrid","Napoli"], ["Chelsea","Lille","Manchester United"]],
  [["Marseille","Valencia","Benfica"], ["Juventus","Lille","Manchester United"]],
  [["Lyon","AC Milan","Schalke 04"], ["Paris Saint-Germain","Manchester City","Bayern Munich"]],
  [["Atlético Madrid","Inter","Borussia Dortmund"], ["FC Barcelona","Sevilla","Monaco"]],
  [["Roma","RB Leipzig","Liverpool"], ["FC Barcelona","Sevilla","Bayer Leverkusen"]],
  [["Roma","Bayer Leverkusen","Liverpool"], ["Real Madrid","Monaco","RB Leipzig"]],
  [["Paris Saint-Germain","Atlético Madrid","Inter"], ["Borussia Dortmund","Manchester United","Lyon"]],
  [["Marseille","Bayern Munich","Schalke 04"], ["Manchester City","Juventus","Lille"]],
  [["Valencia","Chelsea","Benfica"], ["Manchester City","Bayern Munich","Arsenal"]],
  [["Valencia","Juventus","Manchester United"], ["Benfica","Napoli","AC Milan"]],
  [["Paris Saint-Germain","FC Barcelona","Chelsea"], ["AC Milan","Napoli","Arsenal"]],
  [["Lyon","Lille","Inter"], ["Real Madrid","Liverpool","Marseille"]],
  [["Marseille","Borussia Dortmund","RB Leipzig"], ["Sevilla","Roma","Bayer Leverkusen"]],
  [["Monaco","Atlético Madrid","Schalke 04"], ["Real Madrid","Manchester City","Paris Saint-Germain"]],
  [["Lille","Atlético Madrid","Roma"], ["Chelsea","Monaco","Sevilla"]],
  [["Inter","Bayer Leverkusen","Schalke 04"], ["FC Barcelona","Bayern Munich","Arsenal"]],
  [["AC Milan","Manchester United","Benfica"], ["Liverpool","Borussia Dortmund","Valencia"]],
  [["Lyon","Napoli","Benfica"], ["Real Madrid","Manchester United","Juventus"]],
  [["Lyon","Juventus","RB Leipzig"], ["AC Milan","Bayern Munich","Roma"]],
  [["Napoli","Borussia Dortmund","RB Leipzig"], ["FC Barcelona","Sevilla","Chelsea"]],
  [["Atlético Madrid","Inter","Bayer Leverkusen"], ["Liverpool","Arsenal","Paris Saint-Germain"]],
  [["Marseille","Monaco","Valencia"], ["Manchester City","Paris Saint-Germain","Lille"]],
  [["Marseille","Inter","Schalke 04"], ["Manchester City","Lille","Arsenal"]],
  [["Atlético Madrid","AC Milan","Schalke 04"], ["FC Barcelona","Valencia","Juventus"]],
  [["Monaco","RB Leipzig","Liverpool"], ["Chelsea","Bayern Munich","Bayer Leverkusen"]],
  [["Napoli","Borussia Dortmund","Liverpool"], ["Sevilla","Manchester United","Roma"]],
  [["Lyon","Napoli","Benfica"], ["Real Madrid","Roma","Juventus"]],
  [["FC Barcelona","AC Milan","Bayern Munich"], ["Real Madrid","Benfica","Lyon"]],
  [["Sevilla","Borussia Dortmund","Manchester United"], ["Atlético Madrid","Manchester City","Inter"]],
  [["Paris Saint-Germain","Lille","Chelsea"], ["Borussia Dortmund","Monaco","Arsenal"]],
  [["Marseille","RB Leipzig","Bayer Leverkusen"], ["Paris Saint-Germain","Bayern Munich","Chelsea"]],
  [["Marseille","Valencia","Schalke 04"], ["Juventus","Lille","FC Barcelona"]],
  [["Real Madrid","Sevilla","Valencia"], ["Schalke 04","Arsenal","Manchester City"]],
  [["Monaco","Atlético Madrid","Roma"], ["Manchester United","Inter","Liverpool"]],
  [["Monaco","FC Barcelona","Roma"], ["AC Milan","Lyon","Bayer Leverkusen"]],
  [["Inter","RB Leipzig","Benfica"], ["AC Milan","Paris Saint-Germain","Liverpool"]],
  [["Real Madrid","Valencia","Juventus"], ["Manchester United","Benfica","Napoli"]],
  [["Napoli","Borussia Dortmund","Schalke 04"], ["Sevilla","Arsenal","Lille"]],
  [["Marseille","RB Leipzig","Arsenal"], ["Manchester City","Bayern Munich","Bayer Leverkusen"]],
  [["Lyon","Atlético Madrid","Manchester City"], ["Chelsea","Bayern Munich","Juventus"]],
  [["Lyon","Sevilla","AC Milan"], ["Chelsea","Atlético Madrid","Marseille"]],
  [["Napoli","RB Leipzig","Bayer Leverkusen"], ["FC Barcelona","Paris Saint-Germain","Roma"]],
  [["Lille","Borussia Dortmund","Benfica"], ["Real Madrid","Inter","Liverpool"]],
  [["Monaco","Valencia","Inter"], ["Real Madrid","Manchester United","Paris Saint-Germain"]],
  [["Valencia","Roma","Schalke 04"], ["Manchester City","Juventus","Arsenal"]],
  [["Marseille","Monaco","Schalke 04"], ["Bayern Munich","Lille","FC Barcelona"]],
  [["Atlético Madrid","Borussia Dortmund","RB Leipzig"], ["AC Milan","Chelsea","Sevilla"]],
  [["Lyon","Napoli","Liverpool"], ["Manchester United","Marseille","Juventus"]],
  [["Bayer Leverkusen","Manchester United","Benfica"], ["Bayern Munich","Real Madrid","Liverpool"]],
  [["Lyon","Bayer Leverkusen","Benfica"], ["Chelsea","Arsenal","Inter"]],
  [["FC Barcelona","Sevilla","Roma"], ["Borussia Dortmund","Napoli","AC Milan"]],
  [["Monaco","RB Leipzig","Schalke 04"], ["FC Barcelona","Manchester City","Paris Saint-Germain"]],
  [["Monaco","Real Madrid","Valencia"], ["Manchester City","Lille","Atlético Madrid"]],
  [["Lille","Atlético Madrid","Schalke 04"], ["Paris Saint-Germain","Juventus","Valencia"]],
  [["Roma","Borussia Dortmund","RB Leipzig"], ["Liverpool","AC Milan","Sevilla"]],
  [["Marseille","Inter","Manchester United"], ["Chelsea","Arsenal","Napoli"]],
  [["Lyon","Bayer Leverkusen","Benfica"], ["FC Barcelona","Bayern Munich","Inter"]],
  [["Lyon","Bayer Leverkusen","Chelsea"], ["Bayern Munich","Liverpool","Marseille"]],
  [["Napoli","Borussia Dortmund","Benfica"], ["Paris Saint-Germain","Manchester United","Roma"]],
  [["Sevilla","Valencia","AC Milan"], ["Real Madrid","Atlético Madrid","Arsenal"]],
  [["Lille","Juventus","Manchester City"], ["Arsenal","Valencia","Schalke 04"]],
  [["Monaco","Juventus","RB Leipzig"], ["Manchester City","AC Milan","Bayern Munich"]],
  [["Paris Saint-Germain","Bayer Leverkusen","Chelsea"], ["Real Madrid","RB Leipzig","Monaco"]],
  [["Lille","Borussia Dortmund","Schalke 04"], ["FC Barcelona","Sevilla","Benfica"]],
  [["Napoli","Roma","Liverpool"], ["Manchester United","Inter","Marseille"]],
  [["Lyon","FC Barcelona","Liverpool"], ["Atlético Madrid","Inter","Marseille"]],
  [["Lyon","Atlético Madrid","Napoli"], ["Chelsea","Manchester United","Paris Saint-Germain"]],
  [["Sevilla","Bayer Leverkusen","Benfica"], ["Real Madrid","Borussia Dortmund","Roma"]],
  [["Monaco","Schalke 04","Arsenal"], ["Lille","Bayern Munich","Juventus"]],
  [["Valencia","AC Milan","RB Leipzig"], ["Manchester City","Sevilla","Bayern Munich"]],
  [["Valencia","Borussia Dortmund","RB Leipzig"], ["FC Barcelona","Manchester City","AC Milan"]],
  [["Monaco","Roma","Schalke 04"], ["Real Madrid","Arsenal","Juventus"]],
  [["Lille","Napoli","Manchester United"], ["Paris Saint-Germain","Chelsea","Marseille"]],
  [["Lyon","Atlético Madrid","Benfica"], ["Real Madrid","Inter","Liverpool"]],
  [["Marseille","Lyon","Bayer Leverkusen"], ["Chelsea","Inter","Liverpool"]],
  [["Atlético Madrid","Bayer Leverkusen","Manchester United"], ["FC Barcelona","Juventus","Paris Saint-Germain"]],
  [["Roma","Schalke 04","Arsenal"], ["Bayern Munich","Lille","Benfica"]],
  [["Valencia","Borussia Dortmund","RB Leipzig"], ["FC Barcelona","Sevilla","AC Milan"]],
  [["Monaco","Napoli","Manchester City"], ["Arsenal","Manchester United","Roma"]],
  [["Monaco","Sevilla","Borussia Dortmund"], ["Manchester City","AC Milan","Inter"]],
  [["Lille","Valencia","Juventus"], ["Napoli","Benfica","Schalke 04"]],
  [["Atlético Madrid","RB Leipzig","Bayer Leverkusen"], ["Liverpool","Bayern Munich","Paris Saint-Germain"]],
  [["Lyon","Bayer Leverkusen","Manchester United"], ["Chelsea","Real Madrid","Marseille"]],
  [["Lyon","Borussia Dortmund","Chelsea"], ["Real Madrid","Manchester City","Marseille"]],
  [["Atlético Madrid","Bayern Munich","RB Leipzig"], ["FC Barcelona","Liverpool","Paris Saint-Germain"]],
  [["Sevilla","Napoli","Schalke 04"], ["Valencia","Juventus","Lille"]],
  [["Paris Saint-Germain","Monaco","Benfica"], ["AC Milan","Inter","Roma"]],
  [["Lyon","Monaco","Inter"], ["AC Milan","Arsenal","Roma"]],
  [["Valencia","Juventus","Schalke 04"], ["Benfica","Lille","Arsenal"]],
  [["Atlético Madrid","Napoli","RB Leipzig"], ["FC Barcelona","Chelsea","Sevilla"]],
  [["Bayer Leverkusen","Manchester City","Manchester United"], ["Bayern Munich","Real Madrid","Marseille"]],
  [["Marseille","Real Madrid","Manchester City"], ["Borussia Dortmund","Liverpool","Sevilla"]],
  [["Bayern Munich","Borussia Dortmund","Liverpool"], ["Juventus","Manchester United","Atlético Madrid"]],
  [["Napoli","RB Leipzig","Bayer Leverkusen"], ["FC Barcelona","Chelsea","Paris Saint-Germain"]],
  [["Lille","Valencia","Arsenal"], ["Inter","Benfica","Schalke 04"]],
  [["AC Milan","Roma","Arsenal"], ["Juventus","Lyon","Monaco"]],
  [["Lyon","Roma","Liverpool"], ["AC Milan","Manchester City","Monaco"]],
  [["Paris Saint-Germain","Lille","Schalke 04"], ["Bayern Munich","Benfica","Valencia"]],
  [["Atlético Madrid","Napoli","Manchester United"], ["FC Barcelona","Chelsea","Inter"]],
  [["Marseille","Borussia Dortmund","RB Leipzig"], ["Chelsea","Sevilla","Bayer Leverkusen"]],
  [["Sevilla","Napoli","Borussia Dortmund"], ["FC Barcelona","Real Madrid","Marseille"]],
  [["Real Madrid","Inter","RB Leipzig"], ["Paris Saint-Germain","Bayer Leverkusen","Liverpool"]],
  [["Monaco","Valencia","Benfica"], ["Bayern Munich","Atlético Madrid","Manchester United"]],
  [["Lyon","AC Milan","Manchester City"], ["Atlético Madrid","Arsenal","Roma"]],
  [["Juventus","Roma","Schalke 04"], ["Arsenal","FC Barcelona","Lille"]],
  [["AC Milan","Schalke 04","Benfica"], ["Lille","Juventus","Valencia"]],
  [["Lyon","Bayern Munich","Manchester United"], ["Real Madrid","Manchester City","Marseille"]],
  [["Sevilla","RB Leipzig","Bayer Leverkusen"], ["Paris Saint-Germain","Chelsea","Liverpool"]],
  [["Monaco","Napoli","Borussia Dortmund"], ["Chelsea","Manchester United","Paris Saint-Germain"]],
  [["Juventus","Inter","Liverpool"], ["Monaco","Bayer Leverkusen","Borussia Dortmund"]],
  [["Inter","Napoli","RB Leipzig"], ["FC Barcelona","Roma","Sevilla"]],
  [["Marseille","Lyon","Real Madrid"], ["Manchester City","Bayern Munich","AC Milan"]],
  [["Lille","Schalke 04","Benfica"], ["Arsenal","Bayern Munich","Valencia"]],
  [["Valencia","Arsenal","Benfica"], ["Atlético Madrid","Inter","Lille"]],
  [["Atlético Madrid","Borussia Dortmund","Schalke 04"], ["Manchester City","Real Madrid","Sevilla"]],
  [["Lyon","FC Barcelona","Roma"], ["AC Milan","Marseille","Monaco"]],
  [["Napoli","Bayer Leverkusen","Liverpool"], ["Chelsea","Juventus","Marseille"]],
  [["AC Milan","RB Leipzig","Manchester United"], ["Chelsea","Paris Saint-Germain","Liverpool"]],
  [["RB Leipzig","Bayer Leverkusen","Manchester United"], ["Bayern Munich","Paris Saint-Germain","Roma"]],
  [["Lyon","Juventus","Napoli"], ["Real Madrid","FC Barcelona","Inter"]],
  [["Valencia","Borussia Dortmund","Manchester City"], ["Atlético Madrid","Sevilla","Arsenal"]],
  [["Sevilla","Arsenal","Benfica"], ["Atlético Madrid","Schalke 04","Lille"]],
  [["Monaco","Borussia Dortmund","Schalke 04"], ["FC Barcelona","Lille","Juventus"]],
  [["Monaco","Manchester City","Benfica"], ["Real Madrid","Bayern Munich","Manchester United"]],
  [["Lyon","Napoli","RB Leipzig"], ["Chelsea","Paris Saint-Germain","Roma"]],
  [["Marseille","Inter","RB Leipzig"], ["Chelsea","AC Milan","Bayer Leverkusen"]],
  [["Valencia","Liverpool","Benfica"], ["Inter","AC Milan","Lille"]],
  [["Valencia","Bayer Leverkusen","Liverpool"], ["FC Barcelona","Real Madrid","Paris Saint-Germain"]],
  [["Monaco","Napoli","Manchester City"], ["Marseille","Manchester United","Roma"]],
  [["Marseille","Lyon","Schalke 04"], ["Juventus","Bayern Munich","Arsenal"]],
  [["Paris Saint-Germain","Sevilla","Juventus"], ["Borussia Dortmund","Atlético Madrid","Schalke 04"]],
  [["FC Barcelona","Atlético Madrid","Manchester City"], ["Borussia Dortmund","Sevilla","Arsenal"]],
  [["Lyon","AC Milan","Roma"], ["Real Madrid","Bayern Munich","Monaco"]],
  [["Lille","Inter","Manchester United"], ["Liverpool","Benfica","Valencia"]],
  [["Napoli","Bayer Leverkusen","Manchester United"], ["Chelsea","Inter","Roma"]],
  [["Lille","RB Leipzig","Bayer Leverkusen"], ["Paris Saint-Germain","Chelsea","Liverpool"]],
  [["Real Madrid","Valencia","RB Leipzig"], ["Bayern Munich","Sevilla","Manchester City"]],
  [["Monaco","Napoli","Borussia Dortmund"], ["Arsenal","Marseille","Juventus"]],
  [["FC Barcelona","Atlético Madrid","Schalke 04"], ["Juventus","Arsenal","Benfica"]],
  [["Lyon","Monaco","Valencia"], ["AC Milan","FC Barcelona","Atlético Madrid"]],
  [["Marseille","Lyon","Benfica"], ["AC Milan","Manchester United","Roma"]],
  [["Napoli","Schalke 04","Manchester City"], ["Sevilla","Paris Saint-Germain","Real Madrid"]],
  [["Napoli","Bayern Munich","Borussia Dortmund"], ["Chelsea","Lille","Inter"]],
  [["Bayer Leverkusen","Manchester City","Liverpool"], ["Bayern Munich","Borussia Dortmund","RB Leipzig"]],
  [["Marseille","Inter","Arsenal"], ["AC Milan","Lille","Liverpool"]],
  [["Real Madrid","FC Barcelona","Sevilla"], ["Atlético Madrid","Chelsea","Roma"]],
  [["Lyon","Monaco","Valencia"], ["Manchester United","Paris Saint-Germain","Juventus"]],
  [["RB Leipzig","Schalke 04","Benfica"], ["Bayern Munich","Paris Saint-Germain","FC Barcelona"]],
  [["Sevilla","Bayer Leverkusen","Benfica"], ["Juventus","Roma","Chelsea"]],
  [["Bayer Leverkusen","Manchester United","Arsenal"], ["Borussia Dortmund","Marseille","Monaco"]],
  [["Lyon","Valencia","Liverpool"], ["Real Madrid","Manchester City","Inter"]],
  [["Lille","Atlético Madrid","RB Leipzig"], ["AC Milan","Sevilla","Liverpool"]],
  [["Lille","Real Madrid","Valencia"], ["Napoli","Juventus","Schalke 04"]],
  [["Napoli","Bayer Leverkusen","Schalke 04"], ["FC Barcelona","Arsenal","Paris Saint-Germain"]],
  [["Atlético Madrid","RB Leipzig","Manchester United"], ["Manchester City","AC Milan","Chelsea"]],
  [["Marseille","Monaco","AC Milan"], ["Borussia Dortmund","Inter","Roma"]],
  [["Lyon","Inter","Benfica"], ["Manchester United","Bayern Munich","Arsenal"]],
  [["Lyon","Schalke 04","Benfica"], ["FC Barcelona","Manchester City","Bayern Munich"]],
  [["Monaco","Lille","Bayer Leverkusen"], ["Borussia Dortmund","Marseille","Roma"]],
  [["Atlético Madrid","RB Leipzig","Chelsea"], ["Liverpool","Sevilla","Paris Saint-Germain"]],
  [["Paris Saint-Germain","Real Madrid","Napoli"], ["Juventus","Sevilla","Valencia"]],
  [["Real Madrid","Napoli","Benfica"], ["Juventus","Roma","Valencia"]],
  [["Marseille","Atlético Madrid","RB Leipzig"], ["Chelsea","FC Barcelona","Liverpool"]],
  [["Monaco","Borussia Dortmund","Schalke 04"], ["Lille","Arsenal","Bayern Munich"]],
  [["Marseille","Lyon","Manchester United"], ["Manchester City","AC Milan","Inter"]],
  [["Lyon","AC Milan","Bayer Leverkusen"], ["Real Madrid","Arsenal","Inter"]],
  [["Paris Saint-Germain","FC Barcelona","Borussia Dortmund"], ["Manchester City","Manchester United","Bayer Leverkusen"]],
  [["Lille","Valencia","Schalke 04"], ["Bayern Munich","Juventus","Sevilla"]],
  [["Monaco","Lille","Benfica"], ["Chelsea","Liverpool","Roma"]],
  [["Atlético Madrid","Napoli","RB Leipzig"], ["FC Barcelona","Chelsea","Paris Saint-Germain"]],
  [["Atlético Madrid","Roma","RB Leipzig"], ["Manchester City","Liverpool","Sevilla"]],
  [["Valencia","Napoli","Benfica"], ["Real Madrid","Inter","Manchester United"]],
  [["Juventus","Borussia Dortmund","Arsenal"], ["Bayern Munich","Monaco","Bayer Leverkusen"]],
  [["Monaco","Juventus","AC Milan"], ["Borussia Dortmund","Marseille","Lyon"]],
  [["Lyon","AC Milan","Schalke 04"], ["Real Madrid","Bayern Munich","Arsenal"]],
  [["Marseille","Napoli","Schalke 04"], ["Paris Saint-Germain","Lille","Sevilla"]],
  [["Atlético Madrid","Valencia","Liverpool"], ["Benfica","Manchester United","Inter"]],
  [["Roma","RB Leipzig","Benfica"], ["Chelsea","FC Barcelona","Manchester City"]],
  [["Marseille","Roma","RB Leipzig"], ["Chelsea","FC Barcelona","Bayer Leverkusen"]],
  [["Valencia","Bayer Leverkusen","Manchester City"], ["Inter","Paris Saint-Germain","Arsenal"]],
  [["Sevilla","Borussia Dortmund","Manchester United"], ["Atlético Madrid","Juventus","Liverpool"]],
  [["Monaco","Real Madrid","Liverpool"], ["AC Milan","Lille","Bayern Munich"]],
  [["Lyon","Napoli","Schalke 04"], ["FC Barcelona","Paris Saint-Germain","Juventus"]],
  [["Napoli","Bayern Munich","Schalke 04"], ["Lille","Real Madrid","Valencia"]],
  [["Lyon","Atlético Madrid","AC Milan"], ["Manchester United","Arsenal","Monaco"]],
  [["Marseille","Sevilla","Bayer Leverkusen"], ["Chelsea","Borussia Dortmund","Inter"]],
  [["Roma","Manchester City","Chelsea"], ["Arsenal","Benfica","RB Leipzig"]],
  [["Paris Saint-Germain","RB Leipzig","Benfica"], ["Manchester City","AC Milan","Roma"]],
  [["Lyon","Borussia Dortmund","Bayer Leverkusen"], ["Inter","Liverpool","Marseille"]],
  [["FC Barcelona","Sevilla","Valencia"], ["Atlético Madrid","Real Madrid","Lille"]],
  [["Monaco","Atlético Madrid","Napoli"], ["Real Madrid","Manchester United","Juventus"]],
  [["Monaco","Schalke 04","Manchester City"], ["FC Barcelona","Bayern Munich","Juventus"]],
  [["Valencia","Bayern Munich","Arsenal"], ["Manchester United","Lille","Schalke 04"]],
  [["Napoli","Borussia Dortmund","Chelsea"], ["Sevilla","Roma","Marseille"]],
  [["Lyon","RB Leipzig","Liverpool"], ["AC Milan","Paris Saint-Germain","Roma"]],
  [["Valencia","Bayer Leverkusen","Benfica"], ["FC Barcelona","Inter","Paris Saint-Germain"]],
  [["Bayern Munich","Chelsea","Arsenal"], ["Bayer Leverkusen","Benfica","Inter"]],
  [["Real Madrid","RB Leipzig","Manchester City"], ["Liverpool","AC Milan","Sevilla"]],
  [["Marseille","Lyon","Juventus"], ["AC Milan","Monaco","Manchester United"]],
  [["Marseille","Borussia Dortmund","Schalke 04"], ["Manchester City","Juventus","Lille"]],
  [["Atlético Madrid","Napoli","Borussia Dortmund"], ["Real Madrid","Manchester United","Paris Saint-Germain"]],
  [["Atlético Madrid","Napoli","Chelsea"], ["FC Barcelona","Sevilla","Inter"]],
  [["Monaco","Bayern Munich","Arsenal"], ["Liverpool","Roma","Bayer Leverkusen"]],
  [["Inter","Schalke 04","Benfica"], ["Valencia","Lille","Arsenal"]],
  [["Lyon","Lille","RB Leipzig"], ["AC Milan","Bayern Munich","Liverpool"]],
  [["Lyon","RB Leipzig","Benfica"], ["Chelsea","FC Barcelona","Roma"]],
  [["Sevilla","Schalke 04","Manchester City"], ["Real Madrid","Paris Saint-Germain","Valencia"]],
  [["Monaco","Bayer Leverkusen","Manchester United"], ["Borussia Dortmund","Marseille","Juventus"]],
  [["Marseille","Atlético Madrid","Napoli"], ["Juventus","FC Barcelona","Manchester United"]],
  [["Atlético Madrid","Valencia","Napoli"], ["Real Madrid","Sevilla","Paris Saint-Germain"]],
  [["AC Milan","Bayern Munich","Bayer Leverkusen"], ["Monaco","Borussia Dortmund","RB Leipzig"]],
  [["Lille","Manchester City","Chelsea"], ["Arsenal","Roma","Benfica"]],
  [["Inter","Liverpool","Chelsea"], ["Roma","Lyon","Bayer Leverkusen"]],
  [["Inter","Schalke 04","Liverpool"], ["FC Barcelona","Benfica","Arsenal"]],
  [["Lyon","RB Leipzig","Schalke 04"], ["Paris Saint-Germain","Manchester City","Bayern Munich"]],
  [["Monaco","Real Madrid","Sevilla"], ["Lille","Borussia Dortmund","Atlético Madrid"]],
  [["Real Madrid","Valencia","Manchester United"], ["Juventus","AC Milan","Napoli"]],
  [["Marseille","Valencia","Juventus"], ["Manchester City","AC Milan","Napoli"]],
  [["Marseille","Atlético Madrid","Manchester United"], ["Paris Saint-Germain","Monaco","Borussia Dortmund"]],
  [["Lille","Inter","Schalke 04"], ["Arsenal","Bayern Munich","Sevilla"]],
  [["Roma","RB Leipzig","Benfica"], ["Chelsea","Liverpool","FC Barcelona"]],
  [["Lyon","RB Leipzig","Bayer Leverkusen"], ["FC Barcelona","Paris Saint-Germain","Liverpool"]],
  [["Lyon","Monaco","Bayer Leverkusen"], ["Chelsea","Roma","Inter"]],
  [["Bayern Munich","Schalke 04","Benfica"], ["Manchester City","Arsenal","Lille"]],
  [["Atlético Madrid","AC Milan","Napoli"], ["Real Madrid","Manchester United","Sevilla"]],
  [["Marseille","Valencia","Borussia Dortmund"], ["Juventus","Bayern Munich","Inter"]],
  [["Lille","Sevilla","AC Milan"], ["Borussia Dortmund","Marseille","Valencia"]],
  [["Atlético Madrid","Napoli","Roma"], ["Real Madrid","Juventus","Manchester United"]],
  [["Schalke 04","Manchester City","Liverpool"], ["Arsenal","Paris Saint-Germain","Benfica"]],
  [["Bayer Leverkusen","Manchester City","Chelsea"], ["RB Leipzig","FC Barcelona","Monaco"]],
  [["Lyon","Bayer Leverkusen","Chelsea"], ["Real Madrid","FC Barcelona","Monaco"]],
  [["Lyon","RB Leipzig","Arsenal"], ["Paris Saint-Germain","Roma","Liverpool"]],
  [["Atlético Madrid","Juventus","Schalke 04"], ["Valencia","Benfica","Sevilla"]],
  [["Marseille","AC Milan","Bayern Munich"], ["Lille","Borussia Dortmund","Manchester United"]],
  [["Marseille","Lille","Juventus"], ["AC Milan","Inter","Napoli"]],
  [["Atlético Madrid","Napoli","Borussia Dortmund"], ["Chelsea","Manchester United","Inter"]],
  [["Valencia","RB Leipzig","Schalke 04"], ["FC Barcelona","Sevilla","Bayern Munich"]],
  [["Paris Saint-Germain","Real Madrid","Roma"], ["Benfica","Monaco","Liverpool"]],
  [["Lyon","Bayer Leverkusen","Manchester City"], ["Paris Saint-Germain","Bayern Munich","Arsenal"]],
  [["Lyon","Monaco","Benfica"], ["Real Madrid","Manchester City","Arsenal"]],
  [["FC Barcelona","Sevilla","Bayer Leverkusen"], ["Borussia Dortmund","Roma","Liverpool"]],
  [["Valencia","AC Milan","Napoli"], ["Inter","Juventus","Manchester United"]],
  [["Lille","Sevilla","Juventus"], ["Chelsea","Marseille","Schalke 04"]],
  [["Atlético Madrid","AC Milan","RB Leipzig"], ["Manchester City","Liverpool","Chelsea"]],
  [["Real Madrid","Borussia Dortmund","Arsenal"], ["Bayern Munich","Inter","Lille"]],
  [["Marseille","Napoli","Roma"], ["Paris Saint-Germain","FC Barcelona","Manchester United"]],
  [["Atlético Madrid","Schalke 04","Benfica"], ["Manchester City","FC Barcelona","Valencia"]],
  [["Lyon","RB Leipzig","Bayer Leverkusen"], ["Chelsea","Paris Saint-Germain","Roma"]],
  [["Atlético Madrid","Bayern Munich","Arsenal"], ["Valencia","Lyon","Monaco"]],
  [["Lille","Juventus","Bayer Leverkusen"], ["Real Madrid","Monaco","Marseille"]],
  [["Inter","Borussia Dortmund","RB Leipzig"], ["AC Milan","Bayer Leverkusen","Sevilla"]],
  [["Schalke 04","Manchester United","Liverpool"], ["Real Madrid","Paris Saint-Germain","Benfica"]],
  [["Napoli","Liverpool","Benfica"], ["Arsenal","Manchester United","Roma"]],
  [["FC Barcelona","Valencia","Juventus"], ["Napoli","Inter","Schalke 04"]],
  [["Marseille","Monaco","Sevilla"], ["Chelsea","AC Milan","Borussia Dortmund"]],
  [["FC Barcelona","Bayern Munich","Manchester City"], ["Atlético Madrid","RB Leipzig","Lyon"]],
  [["Lille","Atlético Madrid","RB Leipzig"], ["Chelsea","Bayern Munich","Sevilla"]],
  [["Lyon","Lille","Manchester City"], ["Paris Saint-Germain","Arsenal","Inter"]],
  [["AC Milan","Borussia Dortmund","Liverpool"], ["Real Madrid","Juventus","Marseille"]],
  [["Valencia","Arsenal","Benfica"], ["Manchester United","AC Milan","Schalke 04"]],
  [["Monaco","Juventus","Roma"], ["Manchester United","Inter","Bayer Leverkusen"]],
  [["Napoli","Bayer Leverkusen","Liverpool"], ["Chelsea","Roma","Real Madrid"]],
  [["Marseille","Lille","FC Barcelona"], ["Monaco","Borussia Dortmund","Napoli"]],
  [["RB Leipzig","Schalke 04","Benfica"], ["Bayern Munich","Paris Saint-Germain","Manchester City"]],
  [["Lyon","Sevilla","Valencia"], ["Real Madrid","FC Barcelona","Atlético Madrid"]],
  [["Paris Saint-Germain","Sevilla","Benfica"], ["Borussia Dortmund","Valencia","Atlético Madrid"]],
  [["Lyon","Monaco","Schalke 04"], ["Manchester City","Bayern Munich","Juventus"]],
  [["Inter","RB Leipzig","Liverpool"], ["AC Milan","Chelsea","Roma"]],
  [["Marseille","Roma","Arsenal"], ["Lille","Liverpool","Napoli"]],
  [["Marseille","Inter","Bayern Munich"], ["Arsenal","Manchester United","Bayer Leverkusen"]],
  [["Lille","Bayer Leverkusen","Manchester United"], ["Paris Saint-Germain","Chelsea","Juventus"]],
  [["Atlético Madrid","Napoli","Manchester City"], ["Real Madrid","Valencia","Sevilla"]],
  [["Lyon","Borussia Dortmund","Manchester City"], ["AC Milan","FC Barcelona","Monaco"]],
  [["AC Milan","RB Leipzig","Schalke 04"], ["Paris Saint-Germain","FC Barcelona","Sevilla"]],
  [["Lille","Borussia Dortmund","Schalke 04"], ["Real Madrid","Bayern Munich","Benfica"]],
  [["Manchester United","Liverpool","Arsenal"], ["Lyon","Benfica","Monaco"]],
  [["Juventus","Napoli","Bayer Leverkusen"], ["Marseille","Inter","Chelsea"]],
  [["Atlético Madrid","Roma","RB Leipzig"], ["FC Barcelona","Chelsea","Bayern Munich"]],
  [["Valencia","Roma","RB Leipzig"], ["Manchester City","Sevilla","Paris Saint-Germain"]],
  [["Atlético Madrid","Juventus","Inter"], ["Valencia","Manchester United","Arsenal"]],
  [["Lille","AC Milan","Bayer Leverkusen"], ["Borussia Dortmund","Marseille","Liverpool"]],
  [["Napoli","Schalke 04","Benfica"], ["Paris Saint-Germain","Juventus","Real Madrid"]],
  [["AC Milan","Roma","Liverpool"], ["Real Madrid","Lyon","Monaco"]],
  [["Marseille","Monaco","Inter"], ["Arsenal","Manchester United","Lyon"]],
  [["Borussia Dortmund","Schalke 04","Benfica"], ["Bayern Munich","FC Barcelona","Lille"]],
  [["Sevilla","Napoli","Manchester City"], ["Valencia","Inter","Chelsea"]],
  [["Atlético Madrid","RB Leipzig","Bayer Leverkusen"], ["FC Barcelona","Liverpool","Paris Saint-Germain"]],
  [["Bayern Munich","Bayer Leverkusen","Manchester City"], ["Real Madrid","RB Leipzig","Chelsea"]],
  [["Sevilla","Valencia","Juventus"], ["Atlético Madrid","Lille","Arsenal"]],
  [["Monaco","Lille","Manchester United"], ["Borussia Dortmund","Marseille","Roma"]],
  [["Lyon","AC Milan","Napoli"], ["Chelsea","Roma","Juventus"]],
  [["AC Milan","Schalke 04","Manchester United"], ["FC Barcelona","Manchester City","Benfica"]],
  [["Valencia","Borussia Dortmund","Schalke 04"], ["Benfica","Paris Saint-Germain","Arsenal"]],
  [["Monaco","Sevilla","Napoli"], ["Real Madrid","Marseille","Inter"]],
  [["Lyon","Atlético Madrid","RB Leipzig"], ["AC Milan","Bayern Munich","Liverpool"]],
  [["RB Leipzig","Bayer Leverkusen","Liverpool"], ["Bayern Munich","FC Barcelona","Roma"]],
  [["Lyon","Atlético Madrid","Bayer Leverkusen"], ["Paris Saint-Germain","Arsenal","Juventus"]],
  [["Lille","Inter","Chelsea"], ["Monaco","Borussia Dortmund","Marseille"]],
  [["Valencia","Napoli","Manchester City"], ["Real Madrid","Inter","Manchester United"]],
  [["Real Madrid","Valencia","Arsenal"], ["Sevilla","Schalke 04","Benfica"]],
  [["Lille","Juventus","Manchester City"], ["Sevilla","Benfica","Schalke 04"]],
  [["Napoli","Borussia Dortmund","Chelsea"], ["Paris Saint-Germain","Manchester United","Marseille"]],
  [["Monaco","Atlético Madrid","Bayern Munich"], ["FC Barcelona","Liverpool","Lyon"]],
  [["Marseille","Bayern Munich","RB Leipzig"], ["AC Milan","Roma","Bayer Leverkusen"]],
  [["Paris Saint-Germain","RB Leipzig","Liverpool"], ["AC Milan","Roma","Bayer Leverkusen"]],
  [["Lyon","Monaco","Borussia Dortmund"], ["Manchester United","FC Barcelona","Atlético Madrid"]],
  [["Sevilla","Napoli","Benfica"], ["Real Madrid","Lille","Chelsea"]],
  [["Sevilla","Juventus","Schalke 04"], ["Valencia","Arsenal","Manchester City"]],
  [["Juventus","Inter","Schalke 04"], ["Arsenal","Benfica","Valencia"]],
  [["Lille","Real Madrid","Manchester City"], ["Chelsea","Borussia Dortmund","Inter"]],
  [["Paris Saint-Germain","FC Barcelona","Manchester United"], ["Marseille","Napoli","Monaco"]],
  [["Lyon","AC Milan","Bayern Munich"], ["Atlético Madrid","Roma","Monaco"]],
  [["Roma","RB Leipzig","Bayer Leverkusen"], ["Liverpool","FC Barcelona","Bayern Munich"]],
  [["AC Milan","Bayer Leverkusen","Manchester City"], ["Chelsea","Liverpool","RB Leipzig"]],
  [["Lyon","Atlético Madrid","Napoli"], ["Manchester United","Arsenal","Inter"]],
  [["Marseille","Real Madrid","Borussia Dortmund"], ["Paris Saint-Germain","Juventus","Lille"]],
  [["Sevilla","Valencia","Benfica"], ["Real Madrid","Schalke 04","AC Milan"]],
  [["FC Barcelona","Inter","Schalke 04"], ["Sevilla","Valencia","Benfica"]],
  [["Lille","Borussia Dortmund","Bayer Leverkusen"], ["Paris Saint-Germain","Marseille","Juventus"]],
  [["Lyon","Napoli","Roma"], ["Chelsea","Manchester United","Arsenal"]],
  [["Monaco","Atlético Madrid","RB Leipzig"], ["Manchester City","Paris Saint-Germain","Liverpool"]],
  [["Monaco","Atlético Madrid","Liverpool"], ["Manchester City","Bayern Munich","Juventus"]],
  [["Lyon","Roma","RB Leipzig"], ["Chelsea","FC Barcelona","Bayern Munich"]],
  [["Real Madrid","Inter","Arsenal"], ["Manchester United","Benfica","Napoli"]],
  [["Marseille","Borussia Dortmund","Arsenal"], ["Lille","Sevilla","Bayer Leverkusen"]],
  [["Paris Saint-Germain","Lille","Valencia"], ["Bayern Munich","AC Milan","Schalke 04"]],
  [["Valencia","Juventus","Manchester City"], ["Manchester United","AC Milan","Schalke 04"]],
  [["Marseille","Real Madrid","Bayer Leverkusen"], ["Borussia Dortmund","Inter","Roma"]],
  [["Monaco","Atlético Madrid","Sevilla"], ["FC Barcelona","Chelsea","Liverpool"]],
  [["Napoli","RB Leipzig","Benfica"], ["FC Barcelona","Chelsea","Paris Saint-Germain"]],
  [["Lyon","Sevilla","Benfica"], ["Real Madrid","Atlético Madrid","Liverpool"]],
  [["Lyon","Monaco","Napoli"], ["Roma","Inter","Juventus"]],
  [["Lille","Borussia Dortmund","Manchester United"], ["AC Milan","Marseille","Bayern Munich"]],
  [["Bayer Leverkusen","Schalke 04","Manchester City"], ["Bayern Munich","Arsenal","Juventus"]],
  [["Valencia","RB Leipzig","Schalke 04"], ["FC Barcelona","Manchester City","Sevilla"]],
  [["Valencia","Borussia Dortmund","Bayer Leverkusen"], ["Real Madrid","Paris Saint-Germain","Arsenal"]],
  [["Monaco","Lille","RB Leipzig"], ["AC Milan","Liverpool","Roma"]],
  [["Marseille","Monaco","Napoli"], ["Chelsea","Manchester United","Inter"]],
  [["Lyon","Real Madrid","Benfica"], ["Atlético Madrid","Roma","Inter"]],
  [["Lyon","Atlético Madrid","Benfica"], ["Chelsea","AC Milan","Juventus"]],
  [["Napoli","Manchester United","Liverpool"], ["FC Barcelona","Paris Saint-Germain","Marseille"]],
  [["Lille","Valencia","Schalke 04"], ["Arsenal","Bayern Munich","Sevilla"]],
  [["Borussia Dortmund","RB Leipzig","Manchester United"], ["Manchester City","Bayern Munich","Liverpool"]],
  [["Bayer Leverkusen","Manchester City","Arsenal"], ["Borussia Dortmund","Paris Saint-Germain","FC Barcelona"]],
];

export function generateGrid(): DuelGrid {
  // A third of grids pit two triples of clubs against each other (a
  // player who turned out for both) instead of club x nationality — same
  // underlying cellCandidates()/matchesCriteria() logic already handles
  // 'club' criteria on both axes, this just needed a second precomputed
  // pool and a coin flip here to pick which kind to deal.
  if (Math.random() < 1 / 3) {
    const [rowClubs, colClubs] = VALID_GRIDS_CLUB_CLUB[Math.floor(Math.random() * VALID_GRIDS_CLUB_CLUB.length)];
    return {
      rows: rowClubs.map((value) => ({ type: 'club', value, label: value })),
      cols: colClubs.map((value) => ({ type: 'club', value, label: value })),
    };
  }
  const [clubValues, natValues] = VALID_GRIDS[Math.floor(Math.random() * VALID_GRIDS.length)];
  return {
    rows: clubValues.map((value) => ({ type: 'club', value, label: value })),
    // `label` here is just the nat code, unused for display (nationality
    // labels are language-dependent — see criterionLabel() below, which
    // resolves the real text at render time via t('nat_' + code)).
    cols: natValues.map((value) => ({ type: 'nat', value, label: value })),
  };
}

// Row/column headers use this instead of reading `.label` directly:
// nationality display text depends on the current app language, which a
// plain data field baked in at grid-generation time can't reflect.
export function criterionLabel(c: Criterion, t: (key: string) => string): string {
  return c.type === 'nat' ? t('nat_' + c.value) : c.value;
}

export const WIN_LINES: number[][] = [
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8],
  [0, 3, 6],
  [1, 4, 7],
  [2, 5, 8],
  [0, 4, 8],
  [2, 4, 6],
];

export type CellOwner = 'creator' | 'opponent' | null;

export function checkWin(cells: CellOwner[], owner: 'creator' | 'opponent'): boolean {
  return WIN_LINES.some((line) => line.every((i) => cells[i] === owner));
}
