// "Duel Grille" — 3x3 Immaculate-Grid-style board (rows = clubs, columns =
// nationality). Two players take turns claiming cells by naming a player who
// satisfies both the row and column criteria and hasn't already been used
// elsewhere in this grid; first to align 3 cells wins, like tic-tac-toe.
import { PLAYERS, Player } from '../data/players';
import { NAT_FR, stripAcc } from './engine';

export type CriterionType = 'club' | 'nat';

export interface Criterion {
  type: CriterionType;
  value: string;
  label: string;
}

export interface DuelGrid {
  rows: Criterion[];
  cols: Criterion[];
}

function playerMatches(p: Player, c: Criterion): boolean {
  if (c.type === 'club') return p.clubs.includes(c.value);
  return p.nat === c.value;
}

export function cellCandidates(rowC: Criterion, colC: Criterion): Player[] {
  return PLAYERS.filter((p) => playerMatches(p, rowC) && playerMatches(p, colC));
}

export function matchesCriteria(name: string, rowC: Criterion, colC: Criterion): Player | null {
  const target = stripAcc(name.trim().toLowerCase());
  if (!target) return null;
  const found = PLAYERS.find((p) => stripAcc(p.n.toLowerCase()) === target);
  if (!found) return null;
  return playerMatches(found, rowC) && playerMatches(found, colC) ? found : null;
}

// Random 3-club × 3-nationality combos almost never give every one of the 9
// cells a real answer on this roster (checked: out of 5000 random combos,
// only 45 had a valid player in every cell) — rejection-sampling that at
// runtime effectively always exhausted its attempt budget and fell back to
// one fixed combo, which is why every grid looked the same. Precomputing the
// valid combos once (offline, verified against players.ts) and picking
// randomly among them fixes both the correctness and the repetition.
//
// Regenerate this list if players.ts changes significantly (new players
// change which club/nationality pairs actually intersect).
const VALID_GRIDS: [string[], string[]][] = [
  [["Manchester City","Paris Saint-Germain","Real Madrid"], ["FR","BR","ES"]],
  [["Manchester City","Paris Saint-Germain","FC Barcelona"], ["FR","AR","BR"]],
  [["Manchester City","Paris Saint-Germain","FC Barcelona"], ["FR","AR","ES"]],
  [["Manchester City","Paris Saint-Germain","FC Barcelona"], ["FR","BR","ES"]],
  [["Manchester City","Paris Saint-Germain","FC Barcelona"], ["AR","BR","ES"]],
  [["Manchester City","Paris Saint-Germain","Manchester United"], ["FR","BR","ES"]],
  [["Manchester City","Paris Saint-Germain","Juventus"], ["FR","AR","BR"]],
  [["Manchester City","Paris Saint-Germain","Juventus"], ["FR","AR","ES"]],
  [["Manchester City","Paris Saint-Germain","Juventus"], ["FR","BR","ES"]],
  [["Manchester City","Paris Saint-Germain","Juventus"], ["AR","BR","ES"]],
  [["Manchester City","Paris Saint-Germain","Atlético Madrid"], ["FR","AR","ES"]],
  [["Manchester City","Paris Saint-Germain","Chelsea"], ["FR","BR","ES"]],
  [["Manchester City","Paris Saint-Germain","AC Milan"], ["FR","BR","ES"]],
  [["Manchester City","Real Madrid","FC Barcelona"], ["FR","PT","BR"]],
  [["Manchester City","Real Madrid","FC Barcelona"], ["FR","PT","ES"]],
  [["Manchester City","Real Madrid","FC Barcelona"], ["FR","BR","ES"]],
  [["Manchester City","Real Madrid","FC Barcelona"], ["PT","BR","ES"]],
  [["Manchester City","Real Madrid","Manchester United"], ["FR","PT","EN"]],
  [["Manchester City","Real Madrid","Manchester United"], ["FR","PT","BR"]],
  [["Manchester City","Real Madrid","Manchester United"], ["FR","PT","ES"]],
  [["Manchester City","Real Madrid","Manchester United"], ["FR","EN","BR"]],
  [["Manchester City","Real Madrid","Manchester United"], ["FR","EN","ES"]],
  [["Manchester City","Real Madrid","Manchester United"], ["FR","BR","ES"]],
  [["Manchester City","Real Madrid","Manchester United"], ["PT","EN","BR"]],
  [["Manchester City","Real Madrid","Manchester United"], ["PT","EN","ES"]],
  [["Manchester City","Real Madrid","Manchester United"], ["PT","BR","ES"]],
  [["Manchester City","Real Madrid","Manchester United"], ["EN","BR","ES"]],
  [["Manchester City","Real Madrid","Juventus"], ["FR","PT","BR"]],
  [["Manchester City","Real Madrid","Juventus"], ["FR","PT","ES"]],
  [["Manchester City","Real Madrid","Juventus"], ["FR","BR","ES"]],
  [["Manchester City","Real Madrid","Juventus"], ["PT","BR","ES"]],
  [["Manchester City","Real Madrid","Atlético Madrid"], ["FR","PT","EN"]],
  [["Manchester City","Real Madrid","Atlético Madrid"], ["FR","PT","ES"]],
  [["Manchester City","Real Madrid","Atlético Madrid"], ["FR","EN","ES"]],
  [["Manchester City","Real Madrid","Atlético Madrid"], ["PT","EN","ES"]],
  [["Manchester City","Real Madrid","Chelsea"], ["FR","EN","BR"]],
  [["Manchester City","Real Madrid","Chelsea"], ["FR","EN","ES"]],
  [["Manchester City","Real Madrid","Chelsea"], ["FR","EN","DE"]],
  [["Manchester City","Real Madrid","Chelsea"], ["FR","BR","ES"]],
  [["Manchester City","Real Madrid","Chelsea"], ["FR","BR","DE"]],
  [["Manchester City","Real Madrid","Chelsea"], ["FR","ES","DE"]],
  [["Manchester City","Real Madrid","Chelsea"], ["EN","BR","ES"]],
  [["Manchester City","Real Madrid","Chelsea"], ["EN","BR","DE"]],
  [["Manchester City","Real Madrid","Chelsea"], ["EN","ES","DE"]],
  [["Manchester City","Real Madrid","Chelsea"], ["BR","ES","DE"]],
  [["Manchester City","Real Madrid","Liverpool"], ["EN","BR","ES"]],
  [["Manchester City","Real Madrid","Bayern Munich"], ["FR","BR","DE"]],
  [["Manchester City","Real Madrid","Arsenal"], ["FR","EN","BR"]],
  [["Manchester City","Real Madrid","Arsenal"], ["FR","EN","DE"]],
  [["Manchester City","Real Madrid","Arsenal"], ["FR","BR","DE"]],
  [["Manchester City","Real Madrid","Arsenal"], ["EN","BR","DE"]],
  [["Manchester City","Real Madrid","AC Milan"], ["FR","PT","EN"]],
  [["Manchester City","Real Madrid","AC Milan"], ["FR","PT","BR"]],
  [["Manchester City","Real Madrid","AC Milan"], ["FR","PT","ES"]],
  [["Manchester City","Real Madrid","AC Milan"], ["FR","EN","BR"]],
  [["Manchester City","Real Madrid","AC Milan"], ["FR","EN","ES"]],
  [["Manchester City","Real Madrid","AC Milan"], ["FR","BR","ES"]],
  [["Manchester City","Real Madrid","AC Milan"], ["PT","EN","BR"]],
  [["Manchester City","Real Madrid","AC Milan"], ["PT","EN","ES"]],
  [["Manchester City","Real Madrid","AC Milan"], ["PT","BR","ES"]],
  [["Manchester City","Real Madrid","AC Milan"], ["EN","BR","ES"]],
  [["Manchester City","Real Madrid","Inter"], ["FR","PT","BR"]],
  [["Manchester City","FC Barcelona","Manchester United"], ["FR","PT","BR"]],
  [["Manchester City","FC Barcelona","Manchester United"], ["FR","PT","ES"]],
  [["Manchester City","FC Barcelona","Manchester United"], ["FR","BR","ES"]],
  [["Manchester City","FC Barcelona","Manchester United"], ["PT","BR","ES"]],
  [["Manchester City","FC Barcelona","Juventus"], ["FR","AR","PT"]],
  [["Manchester City","FC Barcelona","Juventus"], ["FR","AR","BR"]],
  [["Manchester City","FC Barcelona","Juventus"], ["FR","AR","ES"]],
  [["Manchester City","FC Barcelona","Juventus"], ["FR","PT","BR"]],
  [["Manchester City","FC Barcelona","Juventus"], ["FR","PT","ES"]],
  [["Manchester City","FC Barcelona","Juventus"], ["FR","BR","ES"]],
  [["Manchester City","FC Barcelona","Juventus"], ["AR","PT","BR"]],
  [["Manchester City","FC Barcelona","Juventus"], ["AR","PT","ES"]],
  [["Manchester City","FC Barcelona","Juventus"], ["AR","BR","ES"]],
  [["Manchester City","FC Barcelona","Juventus"], ["PT","BR","ES"]],
  [["Manchester City","FC Barcelona","Atlético Madrid"], ["FR","AR","PT"]],
  [["Manchester City","FC Barcelona","Atlético Madrid"], ["FR","AR","ES"]],
  [["Manchester City","FC Barcelona","Atlético Madrid"], ["FR","PT","ES"]],
  [["Manchester City","FC Barcelona","Atlético Madrid"], ["AR","PT","ES"]],
  [["Manchester City","FC Barcelona","Chelsea"], ["FR","BR","ES"]],
  [["Manchester City","FC Barcelona","AC Milan"], ["FR","PT","BR"]],
  [["Manchester City","FC Barcelona","AC Milan"], ["FR","PT","ES"]],
  [["Manchester City","FC Barcelona","AC Milan"], ["FR","BR","ES"]],
  [["Manchester City","FC Barcelona","AC Milan"], ["PT","BR","ES"]],
  [["Manchester City","FC Barcelona","Inter"], ["FR","PT","BR"]],
  [["Manchester City","FC Barcelona","Benfica"], ["AR","PT","BR"]],
  [["Manchester City","Manchester United","Juventus"], ["FR","PT","BR"]],
  [["Manchester City","Manchester United","Juventus"], ["FR","PT","ES"]],
  [["Manchester City","Manchester United","Juventus"], ["FR","BR","ES"]],
  [["Manchester City","Manchester United","Juventus"], ["PT","BR","ES"]],
  [["Manchester City","Manchester United","Atlético Madrid"], ["FR","PT","EN"]],
  [["Manchester City","Manchester United","Atlético Madrid"], ["FR","PT","ES"]],
  [["Manchester City","Manchester United","Atlético Madrid"], ["FR","EN","ES"]],
  [["Manchester City","Manchester United","Atlético Madrid"], ["PT","EN","ES"]],
  [["Manchester City","Manchester United","Chelsea"], ["FR","EN","BR"]],
  [["Manchester City","Manchester United","Chelsea"], ["FR","EN","ES"]],
  [["Manchester City","Manchester United","Chelsea"], ["FR","BR","ES"]],
  [["Manchester City","Manchester United","Chelsea"], ["EN","BR","ES"]],
  [["Manchester City","Manchester United","Liverpool"], ["EN","BR","ES"]],
  [["Manchester City","Manchester United","Arsenal"], ["FR","EN","BR"]],
  [["Manchester City","Manchester United","AC Milan"], ["FR","PT","EN"]],
  [["Manchester City","Manchester United","AC Milan"], ["FR","PT","BR"]],
  [["Manchester City","Manchester United","AC Milan"], ["FR","PT","ES"]],
  [["Manchester City","Manchester United","AC Milan"], ["FR","EN","BR"]],
  [["Manchester City","Manchester United","AC Milan"], ["FR","EN","ES"]],
  [["Manchester City","Manchester United","AC Milan"], ["FR","BR","ES"]],
  [["Manchester City","Manchester United","AC Milan"], ["PT","EN","BR"]],
  [["Manchester City","Manchester United","AC Milan"], ["PT","EN","ES"]],
  [["Manchester City","Manchester United","AC Milan"], ["PT","BR","ES"]],
  [["Manchester City","Manchester United","AC Milan"], ["EN","BR","ES"]],
  [["Manchester City","Manchester United","Inter"], ["FR","PT","BR"]],
  [["Manchester City","Juventus","Atlético Madrid"], ["FR","AR","PT"]],
  [["Manchester City","Juventus","Atlético Madrid"], ["FR","AR","ES"]],
  [["Manchester City","Juventus","Atlético Madrid"], ["FR","PT","ES"]],
  [["Manchester City","Juventus","Atlético Madrid"], ["AR","PT","ES"]],
  [["Manchester City","Juventus","Chelsea"], ["FR","BR","ES"]],
  [["Manchester City","Juventus","AC Milan"], ["FR","PT","BR"]],
  [["Manchester City","Juventus","AC Milan"], ["FR","PT","ES"]],
  [["Manchester City","Juventus","AC Milan"], ["FR","BR","ES"]],
  [["Manchester City","Juventus","AC Milan"], ["PT","BR","ES"]],
  [["Manchester City","Juventus","Inter"], ["FR","PT","BR"]],
  [["Manchester City","Juventus","Benfica"], ["AR","PT","BR"]],
  [["Manchester City","Atlético Madrid","Chelsea"], ["FR","EN","ES"]],
  [["Manchester City","Atlético Madrid","AC Milan"], ["FR","PT","EN"]],
  [["Manchester City","Atlético Madrid","AC Milan"], ["FR","PT","ES"]],
  [["Manchester City","Atlético Madrid","AC Milan"], ["FR","EN","ES"]],
  [["Manchester City","Atlético Madrid","AC Milan"], ["PT","EN","ES"]],
  [["Manchester City","Chelsea","Liverpool"], ["EN","BR","ES"]],
  [["Manchester City","Chelsea","Bayern Munich"], ["FR","BR","DE"]],
  [["Manchester City","Chelsea","Arsenal"], ["FR","EN","BR"]],
  [["Manchester City","Chelsea","Arsenal"], ["FR","EN","DE"]],
  [["Manchester City","Chelsea","Arsenal"], ["FR","BR","DE"]],
  [["Manchester City","Chelsea","Arsenal"], ["EN","BR","DE"]],
  [["Manchester City","Chelsea","AC Milan"], ["FR","EN","BR"]],
  [["Manchester City","Chelsea","AC Milan"], ["FR","EN","ES"]],
  [["Manchester City","Chelsea","AC Milan"], ["FR","BR","ES"]],
  [["Manchester City","Chelsea","AC Milan"], ["EN","BR","ES"]],
  [["Manchester City","Liverpool","AC Milan"], ["EN","BR","ES"]],
  [["Manchester City","Bayern Munich","Arsenal"], ["FR","BR","DE"]],
  [["Manchester City","Arsenal","AC Milan"], ["FR","EN","BR"]],
  [["Manchester City","AC Milan","Inter"], ["FR","PT","BR"]],
  [["Paris Saint-Germain","Real Madrid","FC Barcelona"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Real Madrid","Manchester United"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Real Madrid","Juventus"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Real Madrid","Chelsea"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Real Madrid","AC Milan"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","FC Barcelona","Manchester United"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","FC Barcelona","Manchester United"], ["FR","BR","NL"]],
  [["Paris Saint-Germain","FC Barcelona","Manchester United"], ["FR","ES","NL"]],
  [["Paris Saint-Germain","FC Barcelona","Manchester United"], ["BR","ES","NL"]],
  [["Paris Saint-Germain","FC Barcelona","Juventus"], ["FR","AR","BR"]],
  [["Paris Saint-Germain","FC Barcelona","Juventus"], ["FR","AR","ES"]],
  [["Paris Saint-Germain","FC Barcelona","Juventus"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","FC Barcelona","Juventus"], ["AR","BR","ES"]],
  [["Paris Saint-Germain","FC Barcelona","Atlético Madrid"], ["FR","AR","ES"]],
  [["Paris Saint-Germain","FC Barcelona","Chelsea"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","FC Barcelona","Liverpool"], ["BR","ES","NL"]],
  [["Paris Saint-Germain","FC Barcelona","AC Milan"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Manchester United","Juventus"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Manchester United","Chelsea"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Manchester United","Liverpool"], ["BR","ES","NL"]],
  [["Paris Saint-Germain","Manchester United","AC Milan"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Juventus","Atlético Madrid"], ["FR","AR","ES"]],
  [["Paris Saint-Germain","Juventus","Chelsea"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Juventus","Chelsea"], ["FR","BR","IT"]],
  [["Paris Saint-Germain","Juventus","Chelsea"], ["FR","ES","IT"]],
  [["Paris Saint-Germain","Juventus","Chelsea"], ["BR","ES","IT"]],
  [["Paris Saint-Germain","Juventus","Liverpool"], ["BR","ES","IT"]],
  [["Paris Saint-Germain","Juventus","AC Milan"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Juventus","AC Milan"], ["FR","BR","IT"]],
  [["Paris Saint-Germain","Juventus","AC Milan"], ["FR","ES","IT"]],
  [["Paris Saint-Germain","Juventus","AC Milan"], ["BR","ES","IT"]],
  [["Paris Saint-Germain","Juventus","Inter"], ["FR","BR","IT"]],
  [["Paris Saint-Germain","Chelsea","Liverpool"], ["BR","ES","IT"]],
  [["Paris Saint-Germain","Chelsea","AC Milan"], ["FR","BR","ES"]],
  [["Paris Saint-Germain","Chelsea","AC Milan"], ["FR","BR","IT"]],
  [["Paris Saint-Germain","Chelsea","AC Milan"], ["FR","ES","IT"]],
  [["Paris Saint-Germain","Chelsea","AC Milan"], ["BR","ES","IT"]],
  [["Paris Saint-Germain","Chelsea","Inter"], ["FR","BR","IT"]],
  [["Paris Saint-Germain","Liverpool","AC Milan"], ["BR","ES","IT"]],
  [["Paris Saint-Germain","AC Milan","Inter"], ["FR","BR","IT"]],
  [["Real Madrid","FC Barcelona","Manchester United"], ["FR","PT","BR"]],
  [["Real Madrid","FC Barcelona","Manchester United"], ["FR","PT","ES"]],
  [["Real Madrid","FC Barcelona","Manchester United"], ["FR","BR","ES"]],
  [["Real Madrid","FC Barcelona","Manchester United"], ["PT","BR","ES"]],
  [["Real Madrid","FC Barcelona","Juventus"], ["FR","PT","BR"]],
  [["Real Madrid","FC Barcelona","Juventus"], ["FR","PT","ES"]],
  [["Real Madrid","FC Barcelona","Juventus"], ["FR","BR","ES"]],
  [["Real Madrid","FC Barcelona","Juventus"], ["PT","BR","ES"]],
  [["Real Madrid","FC Barcelona","Atlético Madrid"], ["FR","PT","ES"]],
  [["Real Madrid","FC Barcelona","Chelsea"], ["FR","BR","ES"]],
  [["Real Madrid","FC Barcelona","AC Milan"], ["FR","PT","BR"]],
  [["Real Madrid","FC Barcelona","AC Milan"], ["FR","PT","ES"]],
  [["Real Madrid","FC Barcelona","AC Milan"], ["FR","BR","ES"]],
  [["Real Madrid","FC Barcelona","AC Milan"], ["PT","BR","ES"]],
  [["Real Madrid","FC Barcelona","Inter"], ["FR","PT","BR"]],
  [["Real Madrid","Manchester United","Juventus"], ["FR","PT","BR"]],
  [["Real Madrid","Manchester United","Juventus"], ["FR","PT","ES"]],
  [["Real Madrid","Manchester United","Juventus"], ["FR","BR","ES"]],
  [["Real Madrid","Manchester United","Juventus"], ["PT","BR","ES"]],
  [["Real Madrid","Manchester United","Atlético Madrid"], ["FR","PT","EN"]],
  [["Real Madrid","Manchester United","Atlético Madrid"], ["FR","PT","ES"]],
  [["Real Madrid","Manchester United","Atlético Madrid"], ["FR","EN","ES"]],
  [["Real Madrid","Manchester United","Atlético Madrid"], ["PT","EN","ES"]],
  [["Real Madrid","Manchester United","Chelsea"], ["FR","EN","BR"]],
  [["Real Madrid","Manchester United","Chelsea"], ["FR","EN","ES"]],
  [["Real Madrid","Manchester United","Chelsea"], ["FR","BR","ES"]],
  [["Real Madrid","Manchester United","Chelsea"], ["EN","BR","ES"]],
  [["Real Madrid","Manchester United","Liverpool"], ["EN","BR","ES"]],
  [["Real Madrid","Manchester United","Arsenal"], ["FR","EN","BR"]],
  [["Real Madrid","Manchester United","AC Milan"], ["FR","PT","EN"]],
  [["Real Madrid","Manchester United","AC Milan"], ["FR","PT","BR"]],
  [["Real Madrid","Manchester United","AC Milan"], ["FR","PT","ES"]],
  [["Real Madrid","Manchester United","AC Milan"], ["FR","EN","BR"]],
  [["Real Madrid","Manchester United","AC Milan"], ["FR","EN","ES"]],
  [["Real Madrid","Manchester United","AC Milan"], ["FR","BR","ES"]],
  [["Real Madrid","Manchester United","AC Milan"], ["PT","EN","BR"]],
  [["Real Madrid","Manchester United","AC Milan"], ["PT","EN","ES"]],
  [["Real Madrid","Manchester United","AC Milan"], ["PT","BR","ES"]],
  [["Real Madrid","Manchester United","AC Milan"], ["EN","BR","ES"]],
  [["Real Madrid","Manchester United","Inter"], ["FR","PT","BR"]],
  [["Real Madrid","Juventus","Atlético Madrid"], ["FR","PT","ES"]],
  [["Real Madrid","Juventus","Chelsea"], ["FR","BR","ES"]],
  [["Real Madrid","Juventus","AC Milan"], ["FR","PT","BR"]],
  [["Real Madrid","Juventus","AC Milan"], ["FR","PT","ES"]],
  [["Real Madrid","Juventus","AC Milan"], ["FR","BR","ES"]],
  [["Real Madrid","Juventus","AC Milan"], ["PT","BR","ES"]],
  [["Real Madrid","Juventus","Inter"], ["FR","PT","BR"]],
  [["Real Madrid","Atlético Madrid","Chelsea"], ["FR","EN","ES"]],
  [["Real Madrid","Atlético Madrid","AC Milan"], ["FR","PT","EN"]],
  [["Real Madrid","Atlético Madrid","AC Milan"], ["FR","PT","ES"]],
  [["Real Madrid","Atlético Madrid","AC Milan"], ["FR","EN","ES"]],
  [["Real Madrid","Atlético Madrid","AC Milan"], ["PT","EN","ES"]],
  [["Real Madrid","Chelsea","Liverpool"], ["EN","BR","ES"]],
  [["Real Madrid","Chelsea","Bayern Munich"], ["FR","BR","DE"]],
  [["Real Madrid","Chelsea","Arsenal"], ["FR","EN","BR"]],
  [["Real Madrid","Chelsea","Arsenal"], ["FR","EN","DE"]],
  [["Real Madrid","Chelsea","Arsenal"], ["FR","BR","DE"]],
  [["Real Madrid","Chelsea","Arsenal"], ["EN","BR","DE"]],
  [["Real Madrid","Chelsea","AC Milan"], ["FR","EN","BR"]],
  [["Real Madrid","Chelsea","AC Milan"], ["FR","EN","ES"]],
  [["Real Madrid","Chelsea","AC Milan"], ["FR","BR","ES"]],
  [["Real Madrid","Chelsea","AC Milan"], ["EN","BR","ES"]],
  [["Real Madrid","Chelsea","Inter"], ["FR","BR","BE"]],
  [["Real Madrid","Liverpool","AC Milan"], ["EN","BR","ES"]],
  [["Real Madrid","Bayern Munich","Arsenal"], ["FR","BR","DE"]],
  [["Real Madrid","Arsenal","AC Milan"], ["FR","EN","BR"]],
  [["Real Madrid","AC Milan","Inter"], ["FR","PT","BR"]],
  [["FC Barcelona","Manchester United","Juventus"], ["FR","PT","BR"]],
  [["FC Barcelona","Manchester United","Juventus"], ["FR","PT","ES"]],
  [["FC Barcelona","Manchester United","Juventus"], ["FR","BR","ES"]],
  [["FC Barcelona","Manchester United","Juventus"], ["PT","BR","ES"]],
  [["FC Barcelona","Manchester United","Atlético Madrid"], ["FR","PT","ES"]],
  [["FC Barcelona","Manchester United","Chelsea"], ["FR","BR","ES"]],
  [["FC Barcelona","Manchester United","Liverpool"], ["BR","ES","NL"]],
  [["FC Barcelona","Manchester United","AC Milan"], ["FR","PT","BR"]],
  [["FC Barcelona","Manchester United","AC Milan"], ["FR","PT","ES"]],
  [["FC Barcelona","Manchester United","AC Milan"], ["FR","BR","ES"]],
  [["FC Barcelona","Manchester United","AC Milan"], ["PT","BR","ES"]],
  [["FC Barcelona","Manchester United","Inter"], ["FR","PT","BR"]],
  [["FC Barcelona","Juventus","Atlético Madrid"], ["FR","AR","PT"]],
  [["FC Barcelona","Juventus","Atlético Madrid"], ["FR","AR","ES"]],
  [["FC Barcelona","Juventus","Atlético Madrid"], ["FR","PT","ES"]],
  [["FC Barcelona","Juventus","Atlético Madrid"], ["AR","PT","ES"]],
  [["FC Barcelona","Juventus","Chelsea"], ["FR","BR","ES"]],
  [["FC Barcelona","Juventus","AC Milan"], ["FR","PT","BR"]],
  [["FC Barcelona","Juventus","AC Milan"], ["FR","PT","ES"]],
  [["FC Barcelona","Juventus","AC Milan"], ["FR","BR","ES"]],
  [["FC Barcelona","Juventus","AC Milan"], ["PT","BR","ES"]],
  [["FC Barcelona","Juventus","Inter"], ["FR","PT","BR"]],
  [["FC Barcelona","Juventus","Benfica"], ["AR","PT","BR"]],
  [["FC Barcelona","Atlético Madrid","AC Milan"], ["FR","PT","ES"]],
  [["FC Barcelona","Chelsea","AC Milan"], ["FR","BR","ES"]],
  [["FC Barcelona","AC Milan","Inter"], ["FR","PT","BR"]],
  [["Manchester United","Juventus","Atlético Madrid"], ["FR","PT","ES"]],
  [["Manchester United","Juventus","Chelsea"], ["FR","BR","ES"]],
  [["Manchester United","Juventus","AC Milan"], ["FR","PT","BR"]],
  [["Manchester United","Juventus","AC Milan"], ["FR","PT","ES"]],
  [["Manchester United","Juventus","AC Milan"], ["FR","BR","ES"]],
  [["Manchester United","Juventus","AC Milan"], ["PT","BR","ES"]],
  [["Manchester United","Juventus","Inter"], ["FR","PT","BR"]],
  [["Manchester United","Atlético Madrid","Chelsea"], ["FR","EN","ES"]],
  [["Manchester United","Atlético Madrid","AC Milan"], ["FR","PT","EN"]],
  [["Manchester United","Atlético Madrid","AC Milan"], ["FR","PT","ES"]],
  [["Manchester United","Atlético Madrid","AC Milan"], ["FR","EN","ES"]],
  [["Manchester United","Atlético Madrid","AC Milan"], ["PT","EN","ES"]],
  [["Manchester United","Chelsea","Liverpool"], ["EN","BR","ES"]],
  [["Manchester United","Chelsea","Arsenal"], ["FR","EN","BR"]],
  [["Manchester United","Chelsea","AC Milan"], ["FR","EN","BR"]],
  [["Manchester United","Chelsea","AC Milan"], ["FR","EN","ES"]],
  [["Manchester United","Chelsea","AC Milan"], ["FR","BR","ES"]],
  [["Manchester United","Chelsea","AC Milan"], ["EN","BR","ES"]],
  [["Manchester United","Liverpool","AC Milan"], ["EN","BR","ES"]],
  [["Manchester United","Arsenal","AC Milan"], ["FR","EN","BR"]],
  [["Manchester United","AC Milan","Inter"], ["FR","PT","BR"]],
  [["Juventus","Atlético Madrid","AC Milan"], ["FR","PT","ES"]],
  [["Juventus","Chelsea","Liverpool"], ["BR","ES","IT"]],
  [["Juventus","Chelsea","AC Milan"], ["FR","BR","ES"]],
  [["Juventus","Chelsea","AC Milan"], ["FR","BR","IT"]],
  [["Juventus","Chelsea","AC Milan"], ["FR","ES","IT"]],
  [["Juventus","Chelsea","AC Milan"], ["BR","ES","IT"]],
  [["Juventus","Chelsea","Inter"], ["FR","BR","IT"]],
  [["Juventus","Liverpool","AC Milan"], ["BR","ES","IT"]],
  [["Juventus","AC Milan","Inter"], ["FR","PT","BR"]],
  [["Juventus","AC Milan","Inter"], ["FR","PT","IT"]],
  [["Juventus","AC Milan","Inter"], ["FR","BR","IT"]],
  [["Juventus","AC Milan","Inter"], ["PT","BR","IT"]],
  [["Atlético Madrid","Chelsea","AC Milan"], ["FR","EN","ES"]],
  [["Chelsea","Liverpool","AC Milan"], ["EN","BR","ES"]],
  [["Chelsea","Liverpool","AC Milan"], ["EN","BR","IT"]],
  [["Chelsea","Liverpool","AC Milan"], ["EN","ES","IT"]],
  [["Chelsea","Liverpool","AC Milan"], ["BR","ES","IT"]],
  [["Chelsea","Bayern Munich","Arsenal"], ["FR","BR","DE"]],
  [["Chelsea","Arsenal","AC Milan"], ["FR","EN","BR"]],
  [["Chelsea","AC Milan","Inter"], ["FR","BR","IT"]],
];

export function generateGrid(): DuelGrid {
  const [clubValues, natValues] = VALID_GRIDS[Math.floor(Math.random() * VALID_GRIDS.length)];
  return {
    rows: clubValues.map((value) => ({ type: 'club', value, label: value })),
    cols: natValues.map((value) => ({ type: 'nat', value, label: NAT_FR[value] || value })),
  };
}

export const WIN_LINES: number[][] = [
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8],
  [0, 3, 6],
  [1, 4, 7],
  [2, 5, 8],
  [0, 4, 8],
  [2, 4, 6],
];

export type CellOwner = 'creator' | 'opponent' | null;

export function checkWin(cells: CellOwner[], owner: 'creator' | 'opponent'): boolean {
  return WIN_LINES.some((line) => line.every((i) => cells[i] === owner));
}
